import type { Context, Game, State } from "./core";
import { canvasPoint, clamp, diff, eventIndex, picked } from "./core";

function surface(host:HTMLElement,w=700,h=430){const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.className="x-canvas";host.appendChild(canvas);return {canvas,ctx:canvas.getContext("2d")!};}
const rect=(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,color:string)=>{ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill();};
const circle=(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,color:string)=>{ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();};

function whack({host,run,rng}:Context):Game {let bug=-1,friendly=false,elapsed=0,show=0,time=45+run.size,lives=3,caught=0,score=0,state:State="playing",message="Whack bugs. Spare the glowing fireflies.",freeze=0;
  const spawn=()=>{bug=Math.floor(rng()*9);friendly=rng()<.18;show=0;};spawn();
  function strike(i:number){if(i!==bug)return;if(friendly){lives--;message="That was a firefly!";}else{caught++;score+=100;message="Nice catch!";}if(caught>=run.size){state="won";message="Bug round cleared!";}else if(lives<=0){state="lost";message="No lives left. Restart to retry.";}spawn();}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${caught}/${run.size} bugs · ${lives} lives · ${Math.ceil(time)}s`},animated:true,render(){host.innerHTML=`<div class="x-panel"><div class="x-board" style="grid-template-columns:repeat(3,1fr);max-width:500px">${Array.from({length:9},(_,i)=>`<button data-hole="${i}" class="x-tile" style="height:115px;border-radius:50%;background:${i===bug?friendly?"#d9f1c8":"#c6dbbd":"#e1eae1"};font-size:52px">${i===bug?friendly?"✦":"✳":""}</button>`).join("")}</div></div>`;},key(k){if(/[1-9]/.test(k))strike(Number(k)-1);},click(e){strike(eventIndex(e,"hole"));},tick(ms){time-=ms/1000;if(time<=0){state="lost";message="Time ran out. Restart to retry.";}if(freeze>0)freeze-=ms;else{show+=ms;if(show>Math.max(550,1550-diff(run)*260-run.level*7)){if(!friendly)lives--;if(lives<=0){state="lost";message="Too many bugs escaped.";}else spawn();}}},lifeline(){freeze=8000;message="Bugs are frozen for eight seconds.";}};
}

function twoCars({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host,560,430);let lanes=[0,0],items:{side:number;lane:number;y:number;good:boolean}[]=[],spawnClock=0,speed=130+diff(run)*35,score=0,caught=0,state:State="playing",message="Switch each car between its two lanes.";
  function switchLane(side:number){lanes[side]=1-lanes[side];}
  function draw(){ctx.clearRect(0,0,560,430);rect(ctx,25,0,510,430,18,"#dce9e5");for(let side=0;side<2;side++){for(let lane=0;lane<2;lane++){const x=100+side*270+lane*95;ctx.strokeStyle="#f8fcf7";ctx.setLineDash([18,16]);ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,430);ctx.stroke();ctx.setLineDash([]);}const x=100+side*270+lanes[side]*95;rect(ctx,x-24,340,48,76,12,side===0?"#d68178":"#719dc0");rect(ctx,x-15,355,30,17,5,"#e5f5f5");}for(const item of items){const x=100+item.side*270+item.lane*95;if(item.good)circle(ctx,x,item.y,18,item.side===0?"#e69d8a":"#8ab6de");else rect(ctx,x-19,item.y-19,38,38,5,"#425967");}}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${caught}/${run.size} pickups`},animated:true,render:draw,key(k){if(k==="a"||k==="arrowleft")switchLane(0);if(k==="d"||k==="arrowright")switchLane(1);},click(e){const p=canvasPoint(e,canvas);switchLane(p.x<280?0:1);},tick(ms){const dt=ms/1000;spawnClock+=ms;speed+=dt*.8;if(spawnClock>Math.max(680,1300-diff(run)*170)){spawnClock=0;const side=Math.floor(rng()*2),lane=Math.floor(rng()*2);items.push({side,lane,y:-25,good:rng()>.3});}for(const item of items){item.y+=speed*dt;if(item.y>=340&&!((item as any).resolved)){(item as any).resolved=true;const hit=lanes[item.side]===item.lane;if((item.good&&!hit)||(!item.good&&hit)){state="lost";message=item.good?"A pickup was missed.":"A car hit a block.";break;}if(item.good){caught++;score+=100;if(caught>=run.size){state="won";message="Both cars made it through!";}}}}items=items.filter(i=>i.y<460);},lifeline(){items=items.filter(i=>i.good);message="Hazards cleared from the road.";}};
}

type Target={x:number;y:number;r:number;age:number;friendly:boolean;id:number};
function targetGame({host,run,rng}:Context,hostage:boolean):Game {const {canvas,ctx}=surface(host,700,430);let targets:Target[]=[],id=0,spawn=0,hits=0,shots=0,lives=3,score=0,state:State="playing",message=hostage?"Shoot enemies, avoid hostages.":"Catch targets before they vanish.",freeze=0,mouse={x:350,y:210};
  function add(){targets.push({x:45+rng()*610,y:55+rng()*315,r:hostage?22:28+diff(run)*4,age:0,friendly:hostage&&rng()<.24,id:id++});}
  add();function fire(x:number,y:number){shots++;const hit=[...targets].reverse().find(t=>Math.hypot(t.x-x,t.y-y)<Math.max(9,t.r-(hostage?0:t.age*.008)));if(!hit){if(hostage){lives--;message="Missed shot.";}return;}targets=targets.filter(t=>t!==hit);if(hit.friendly){lives--;message="Hostage hit!";}else{hits++;score+=Math.max(30,120-Math.floor(hit.age/20));message="Target down.";}if(hits>=run.size){state="won";message=hostage?"Area secured!":"Target round cleared!";}else if(lives<=0){state="lost";message="No lives left. Restart to retry.";}if(!targets.length)add();}
  function draw(){ctx.clearRect(0,0,700,430);rect(ctx,0,0,700,430,14,hostage?"#e7e9de":"#e6e8ee");for(let i=0;i<6;i++)rect(ctx,25+i*115,330+(i%2)*18,82,95,8,hostage?"#aabcb1":"#c1c9d4");for(const t of targets){const r=Math.max(8,t.r-(hostage?0:t.age*.008));circle(ctx,t.x,t.y,r,t.friendly?"#86b19e":hostage?"#c77a70":"#a779b1");circle(ctx,t.x,t.y,r*.63,t.friendly?"#e8f2e2":"#f3eee7");circle(ctx,t.x,t.y,r*.3,t.friendly?"#86b19e":hostage?"#654b51":"#a779b1");}ctx.strokeStyle="#475a62";ctx.lineWidth=2;ctx.beginPath();ctx.arc(mouse.x,mouse.y,12,0,Math.PI*2);ctx.moveTo(mouse.x-18,mouse.y);ctx.lineTo(mouse.x+18,mouse.y);ctx.moveTo(mouse.x,mouse.y-18);ctx.lineTo(mouse.x,mouse.y+18);ctx.stroke();}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${hits}/${run.size} hits · ${lives} lives · ${shots?Math.round(hits/shots*100):100}% accuracy`},animated:true,render:draw,key(){},click(e){const p=canvasPoint(e,canvas);fire(p.x,p.y);},move(e){mouse=canvasPoint(e,canvas);},tick(ms){if(freeze>0)freeze-=ms;else{spawn+=ms;for(const t of targets)t.age+=ms;const lifetime=hostage?2300-diff(run)*300:1900-diff(run)*250;const escaped=targets.filter(t=>t.age>lifetime);targets=targets.filter(t=>t.age<=lifetime);lives-=escaped.filter(t=>!t.friendly).length;if(lives<=0){state="lost";message="Too many targets escaped.";}if(spawn>Math.max(500,1200-diff(run)*200)){spawn=0;if(targets.length<4)add();}}},lifeline(){if(hostage){freeze=7000;message="Targets frozen for seven seconds.";}else{for(const t of targets){t.r+=18;t.age=0;}message="Targets widened.";}}};
}

function flappy({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host,700,430);let bird={x:165,y:210,vy:0},pipes:{x:number;gap:number;passed:boolean}[]=[],spawn=0,passed=0,score=0,state:State="playing",message="Space or click to flap.",slow=0;
  const flap=()=>{bird.vy=-255;};
  function draw(){ctx.clearRect(0,0,700,430);rect(ctx,0,0,700,430,0,"#d7e9e9");for(let i=0;i<5;i++)circle(ctx,(i*177+75)%750,85+i%2*20,28,"#f2f7ef");for(const p of pipes){rect(ctx,p.x,0,62,p.gap-78,5,"#78a692");rect(ctx,p.x,p.gap+78,62,430-p.gap-78,5,"#78a692");rect(ctx,p.x-5,p.gap-94,72,16,3,"#5b8e79");rect(ctx,p.x-5,p.gap+78,72,16,3,"#5b8e79");}circle(ctx,bird.x,bird.y,20,"#e6ba6e");circle(ctx,bird.x+7,bird.y-4,4,"#293f47");ctx.fillStyle="#bd7659";ctx.beginPath();ctx.moveTo(bird.x+18,bird.y);ctx.lineTo(bird.x+35,bird.y+5);ctx.lineTo(bird.x+18,bird.y+9);ctx.fill();}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${passed}/${run.size} pipes`},animated:true,render:draw,key(k){if(k===" "||k==="arrowup"||k==="w")flap();},click(){flap();},tick(ms){const dt=ms/1000;bird.vy+=600*dt;bird.y+=bird.vy*dt;if(bird.y<16||bird.y>414){state="lost";message="The bird fell. Restart to retry.";}spawn+=ms;const speed=(130+diff(run)*28+run.level*2)*(slow>0?.58:1);if(slow>0)slow-=ms;if(spawn>1450){spawn=0;pipes.push({x:720,gap:120+rng()*190,passed:false});}for(const p of pipes){p.x-=speed*dt;if(!p.passed&&p.x+62<bird.x){p.passed=true;passed++;score+=100;if(passed>=run.size){state="won";message="All gaps cleared!";}}if(bird.x+17>p.x&&bird.x-17<p.x+62&&(bird.y-17<p.gap-78||bird.y+17>p.gap+78)){state="lost";message="A pipe was hit. Restart to retry.";}}pipes=pipes.filter(p=>p.x>-70);},lifeline(){slow=9000;message="Pipes slowed for nine seconds.";}};
}

function dino({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host,700,430);let y=0,vy=0,duck=false,obstacles:{x:number;kind:"cactus"|"bird";size:number}[]=[],spawn=0,distance=0,score=0,state:State="playing",message="Jump cacti and duck under birds.",shield=false;
  function draw(){ctx.clearRect(0,0,700,430);rect(ctx,0,0,700,430,0,"#edf1ee");ctx.strokeStyle="#768b85";ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,365);ctx.lineTo(700,365);ctx.stroke();for(let i=0;i<12;i++)rect(ctx,(i*90-distance%90),368,32,3,1,"#9caea7");rect(ctx,110,315-y+(duck?24:0),44,duck?24:50,6,shield?"#85b5c9":"#627c78");circle(ctx,142,325-y+(duck?24:0),3,"#f7f9f4");for(const o of obstacles){if(o.kind==="cactus"){rect(ctx,o.x,365-o.size,27,o.size,6,"#6b9c75");rect(ctx,o.x-10,340-o.size/2,10,25,4,"#6b9c75");}else{ctx.fillStyle="#8d8899";ctx.beginPath();ctx.moveTo(o.x,310);ctx.lineTo(o.x+38,310);ctx.lineTo(o.x+20,325);ctx.fill();}}}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${Math.floor(distance)}/${run.size} m`},animated:true,render:draw,key(k){if([" ","arrowup","w"].includes(k)&&y===0){vy=440;duck=false;}if(k==="arrowdown"||k==="s")duck=true;else if(k==="arrowup"||k===" ")duck=false;},click(){if(y===0){vy=440;duck=false;}},tick(ms){const dt=ms/1000,speed=170+diff(run)*35+distance*.08;distance+=speed*dt/8;score=Math.floor(distance);if(distance>=run.size){state="won";message="Distance goal reached!";}if(y>0||vy>0){y+=vy*dt;vy-=950*dt;if(y<0){y=0;vy=0;}}spawn+=ms;if(spawn>Math.max(700,1450-diff(run)*180)){spawn=0;obstacles.push({x:730,kind:rng()<.3?"bird":"cactus",size:35+rng()*25});}for(const o of obstacles){o.x-=speed*dt;const collision=o.x<152&&o.x+30>110&&(o.kind==="cactus"?y<o.size-8:y>0?y<70:!duck);if(collision){if(shield){shield=false;o.x=-100;message="Shield absorbed a hit.";}else{state="lost";message="Obstacle hit. Restart to retry.";}}}obstacles=obstacles.filter(o=>o.x>-50);},lifeline(){shield=true;message="Shield active for one hit.";}};
}

export const arcadeFactories:Record<string,(ctx:Context)=>Game>={"whack-a-bug":whack,"two-cars":twoCars,"tee-shooter":ctx=>targetGame(ctx,true),"tap-target":ctx=>targetGame(ctx,false),flappy,"chrome-dino":dino};
