import type { Context, Game, State } from "./core";
import { canvasPoint, clamp, diff } from "./core";

function surface(host:HTMLElement,w=700,h=430){const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.className="x-canvas";host.appendChild(canvas);return {canvas,ctx:canvas.getContext("2d")!};}
function box(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,color:string){ctx.fillStyle=color;ctx.fillRect(x,y,w,h);}
function ball(ctx:CanvasRenderingContext2D,x:number,y:number,r:number,color:string){ctx.fillStyle=color;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();}

function trench({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host);type Enemy={x:number;y:number;hp:number;speed:number};let enemies:Enemy[]=[],bullets:{x:number;y:number;vx:number;vy:number}[]=[],aim={x:350,y:120},wave=1,spawned=0,spawnClock=0,health=100,score=0,state:State="playing",message="Defend the trench. Aim and fire.";
  const waveCount=()=>4+wave*2+diff(run)*2;
  function fire(){const dx=aim.x-350,dy=aim.y-378,d=Math.hypot(dx,dy)||1;bullets.push({x:350,y:375,vx:dx/d*440,vy:dy/d*440});}
  function draw(){ctx.clearRect(0,0,700,430);box(ctx,0,0,700,430,"#e7e9db");for(let i=0;i<8;i++)box(ctx,i*110-20,40+i%2*32,55,14,"#d0dac8");box(ctx,0,382,700,48,"#718c78");box(ctx,0,375,700,8,"#536f61");ball(ctx,350,378,24,"#415f5c");ctx.strokeStyle="#536a68";ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(350,375);ctx.lineTo(aim.x,aim.y);ctx.stroke();for(const e of enemies){ball(ctx,e.x,e.y,15,e.hp>1?"#9c6b65":"#c98f7a");box(ctx,e.x-15,e.y-22,30*e.hp/(1+diff(run)),3,"#709983");}for(const b of bullets)ball(ctx,b.x,b.y,5,"#dfb770");box(ctx,18,16,Math.max(0,health)*2,10,"#77a68d");}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `Wave ${wave}/${run.size} · Base ${Math.ceil(health)}%`},animated:true,render:draw,key(k){if(k===" "||k==="enter")fire();if(k==="a"||k==="arrowleft")aim.x=clamp(aim.x-25,20,680);if(k==="d"||k==="arrowright")aim.x=clamp(aim.x+25,20,680);},click(e){aim=canvasPoint(e,canvas);fire();},move(e){aim=canvasPoint(e,canvas);},tick(ms){const dt=ms/1000;spawnClock+=ms;if(spawned<waveCount()&&spawnClock>Math.max(400,1100-diff(run)*150-wave*25)){spawnClock=0;spawned++;enemies.push({x:30+rng()*640,y:-20,hp:1+Math.floor(rng()*(diff(run)+1)),speed:24+wave*5+diff(run)*8+rng()*13});}for(const e of enemies)e.y+=e.speed*dt;for(const b of bullets){b.x+=b.vx*dt;b.y+=b.vy*dt;for(const e of enemies)if(e.hp>0&&Math.hypot(b.x-e.x,b.y-e.y)<19){e.hp--;b.y=-99;if(e.hp<=0){score+=100;message="Enemy stopped.";}break;}}for(const e of enemies)if(e.y>=370&&e.hp>0){health-=15;e.hp=0;message="Enemy reached the trench.";}enemies=enemies.filter(e=>e.hp>0);bullets=bullets.filter(b=>b.y>-20&&b.x>-20&&b.x<720);if(health<=0){state="lost";message="The base fell. Restart to retry.";}else if(spawned>=waveCount()&&!enemies.length){if(wave>=run.size){state="won";message="All waves held!";score+=health*10;}else{wave++;spawned=0;health=Math.min(100,health+5);message=`Wave ${wave} incoming.`;}}},lifeline(){health=Math.min(100,health+40);message="Base repaired by 40%.";}};
}

function hockey({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host);let player={x:150,y:215},ai={x:550,y:215},puck={x:350,y:215,vx:(rng()<.5?-1:1)*160,vy:70},goals=[0,0],score=0,state:State="playing",message="Move your mallet and score past the computer.",wide=0;
  function reset(dir:number){puck={x:350,y:215,vx:dir*145,vy:(rng()-.5)*140};player={x:150,y:215};ai={x:550,y:215};}
  function draw(){ctx.clearRect(0,0,700,430);box(ctx,0,0,700,430,"#d9edeb");ctx.strokeStyle="#95bdbc";ctx.lineWidth=4;ctx.strokeRect(18,18,664,394);ctx.beginPath();ctx.moveTo(350,18);ctx.lineTo(350,412);ctx.arc(350,215,70,0,Math.PI*2);ctx.stroke();box(ctx,0,155,18,120,"#446a6d");box(ctx,682,155,18,120,"#446a6d");ball(ctx,player.x,player.y,wide>0?42:31,"#6193a2");ball(ctx,player.x,player.y,13,"#d5eef0");ball(ctx,ai.x,ai.y,31,"#bd807b");ball(ctx,ai.x,ai.y,13,"#f0d2c8");ball(ctx,puck.x,puck.y,13,"#354b50");}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `You ${goals[0]} : ${goals[1]} Computer · First to ${run.size}`},animated:true,render:draw,key(k){if(k==="w"||k==="arrowup")player.y=clamp(player.y-25,50,380);if(k==="s"||k==="arrowdown")player.y=clamp(player.y+25,50,380);if(k==="a"||k==="arrowleft")player.x=clamp(player.x-25,40,330);if(k==="d"||k==="arrowright")player.x=clamp(player.x+25,40,330);},click(e){const p=canvasPoint(e,canvas);player.x=clamp(p.x,40,330);player.y=clamp(p.y,40,390);},move(e){const p=canvasPoint(e,canvas);player.x=clamp(p.x,40,330);player.y=clamp(p.y,40,390);},tick(ms){const dt=ms/1000;if(wide>0)wide-=ms;ai.y+=clamp(puck.y-ai.y,-(1.5+diff(run))*80*dt,(1.5+diff(run))*80*dt);ai.x=clamp(ai.x+(puck.x>350?clamp(puck.x-ai.x,-1,1)*110*dt:(550-ai.x)*dt),390,650);puck.x+=puck.vx*dt;puck.y+=puck.vy*dt;if(puck.y<31||puck.y>399){puck.vy*=-1;puck.y=clamp(puck.y,31,399);}for(const [m,r] of [[player,wide>0?42:31],[ai,31]] as const){const dx=puck.x-m.x,dy=puck.y-m.y,d=Math.hypot(dx,dy);if(d<r+13&&d>0){const power=Math.max(190,Math.hypot(puck.vx,puck.vy)*1.06);puck.vx=dx/d*power;puck.vy=dy/d*power;puck.x=m.x+dx/d*(r+14);puck.y=m.y+dy/d*(r+14);}}if(puck.x<14||puck.x>686){if(puck.y>155&&puck.y<275){const own=puck.x>350;goals[own?0:1]++;score=goals[0]*250;message=own?"Goal!":"Computer scored.";if(goals[0]>=run.size){state="won";message="You won the match!";}else if(goals[1]>=run.size){state="lost";message="Computer won. Restart to retry.";}reset(own?-1:1);}else{puck.vx*=-1;puck.x=clamp(puck.x,14,686);}}},lifeline(){wide=15000;message="Your mallet is wider for 15 seconds.";}};
}

function survivor({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host);let player={x:350,y:215},enemies:{x:number;y:number;hp:number}[]=[],pickups:{x:number;y:number}[]=[],keys=new Set<string>(),time=0,spawn=0,shot=0,health=3,hurt=0,kills=0,score=0,state:State="playing",message="Move to survive. Weapons fire automatically.";
  function draw(){ctx.clearRect(0,0,700,430);box(ctx,0,0,700,430,"#e4eee6");for(let i=0;i<14;i++)ball(ctx,(i*191)%700,(i*113)%430,2,"#bed1bf");for(const p of pickups){ball(ctx,p.x,p.y,10,"#a8d59c");ctx.fillStyle="#315a41";ctx.fillText("+",p.x-4,p.y+4);}for(const e of enemies)ball(ctx,e.x,e.y,12,e.hp>1?"#965f79":"#b47e8d");ball(ctx,player.x,player.y,17,"#5b98a2");ball(ctx,player.x+5,player.y-5,4,"#e5f8ee");for(let i=0;i<health;i++)ball(ctx,28+i*25,24,8,"#da8b80");}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${Math.floor(time)}/${run.size}s · ${health} hearts · ${kills} foes`},animated:true,render:draw,key(k){keys.add(k);},keyup(k){keys.delete(k);},click(){},tick(ms){const dt=ms/1000;time+=dt;hurt=Math.max(0,hurt-ms);if(time>=run.size){state="won";score+=1000;message="You survived the swarm!";return;}const dx=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),dy=(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0),mag=Math.hypot(dx,dy)||1;player.x=clamp(player.x+dx/mag*180*dt,20,680);player.y=clamp(player.y+dy/mag*180*dt,20,410);spawn+=ms;if(spawn>Math.max(350,1100-diff(run)*170-time*3)){spawn=0;const side=Math.floor(rng()*4);enemies.push({x:side===0?-20:side===1?720:rng()*700,y:side===2?-20:side===3?450:rng()*430,hp:1+(rng()<.16+diff(run)*.08?1:0)});}for(const e of enemies){const vx=player.x-e.x,vy=player.y-e.y,d=Math.hypot(vx,vy)||1;e.x+=vx/d*(45+diff(run)*12+time*.7)*dt;e.y+=vy/d*(45+diff(run)*12+time*.7)*dt;if(d<26&&hurt<=0){health--;hurt=1600;e.hp=0;message="Hit! Keep moving.";}}shot+=ms;if(shot>430&&enemies.length){shot=0;const e=enemies.reduce((a,b)=>Math.hypot(a.x-player.x,a.y-player.y)<Math.hypot(b.x-player.x,b.y-player.y)?a:b);e.hp--;if(e.hp<=0){kills++;score+=50;if(rng()<.12)pickups.push({x:e.x,y:e.y});}}enemies=enemies.filter(e=>e.hp>0);pickups=pickups.filter(p=>{if(Math.hypot(p.x-player.x,p.y-player.y)<22){health=Math.min(4,health+1);message="Health collected.";return false;}return true;});if(health<=0){state="lost";message="The swarm caught you. Restart to retry.";}},lifeline(){health=Math.min(4,health+2);message="Two hearts restored.";}};
}

function sky({host,run,rng}:Context):Game {const {canvas,ctx}=surface(host);type Platform={x:number;y:number;w:number};let platforms:Platform[]=[{x:255,y:380,w:190}],player={x:320,y:345,vx:0,vy:0},camera=0,maxHeight=0,score=0,state:State="playing",message="Climb from platform to platform.",save=false,keys=new Set<string>();for(let i=1;i<15;i++)platforms.push({x:45+rng()*520,y:380-i*80,w:95+rng()*70});
  function draw(){ctx.clearRect(0,0,700,430);box(ctx,0,0,700,430,"#d9ebef");for(let i=0;i<7;i++)ball(ctx,(i*171+80)%700,(i*111+70)%430,24,"#f0f8f4");for(const p of platforms){const y=p.y+camera;if(y>-20&&y<450){box(ctx,p.x,y,p.w,12,"#779f91");box(ctx,p.x+5,y+12,p.w-10,5,"#a5c7ab");}}ball(ctx,player.x,player.y+camera,16,"#e0a679");box(ctx,player.x-8,player.y+camera+10,16,20,"#729cad");}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${Math.floor(maxHeight)}/${run.size} height`},animated:true,render:draw,key(k){if(["a","d","arrowleft","arrowright"," ","w","arrowup"].includes(k)){keys.add(k);}if((k===" "||k==="w"||k==="arrowup")&&Math.abs(player.vy)<1)player.vy=-500;},keyup(k){keys.delete(k);},click(){},tick(ms){const dt=ms/1000;const dir=(keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0);player.x=clamp(player.x+dir*220*dt,15,685);const oldY=player.y;player.vy+=950*dt;player.y+=player.vy*dt;if(player.vy>0)for(const p of platforms)if(oldY+24<=p.y&&player.y+24>=p.y&&player.x+14>p.x&&player.x-14<p.x+p.w){player.y=p.y-24;player.vy=-500;break;}maxHeight=Math.max(maxHeight,380-player.y);score=Math.floor(maxHeight);if(maxHeight>=run.size){state="won";message="You reached the sky goal!";}camera=Math.max(camera,215-player.y);if(player.y+camera>470){if(save){save=false;player.y=215-camera;player.vy=-480;message="Fall saved!";}else{state="lost";message="You fell. Restart to retry.";}}while(platforms.at(-1)!.y>player.y-800){const top=platforms.at(-1)!;platforms.push({x:45+rng()*520,y:top.y-(65+rng()*35),w:90+rng()*70});}platforms=platforms.filter(p=>p.y+camera<500);},lifeline(){save=true;message="Your next fall will be saved.";}};
}

export const arenaFactories:Record<string,(ctx:Context)=>Game>={"trench-defence":trench,"air-hockey":hockey,survivor,"sky-high":sky};
