import { Chess } from "chess.js";
import type { Context, Game, State } from "./core";
import { clamp, diff, eventIndex, picked, shuffle } from "./core";

const WORD_BANKS = ["PLANET,PLANE,PLANT,PANEL,LATE,TALE,LEAP,PEAL", "STREAM,MASTER,STEAM,TEAMS,MEATS,SEAT,TEAM,EAST", "GARDEN,DANGER,GRAND,RANGE,ANGER,READ,DEAR,EARN", "SILENT,LISTEN,INLET,TILES,LINES,LINE,LENT,TILE", "POCKET,TOP,POKE,COKE,POET,COPE,TOE,POT", "CASTLE,SCALE,STALE,STEAL,TALES,LACE,SEAL,TEA", "ORANGE,RANGE,ANGER,GEAR,NEAR,EARN,GOER,ORE", "SPRING,RINGS,GRINS,SPIN,RING,GRIP,PINS,PIG", "BRIGHT,BIRTH,RIGHT,GIRTH,BRIG,TRIG,RIB,BIG", "MARKET,MAKER,TAKER,TEAM,MAKE,TAKE,TEAR,MARK", "FLOWER,LOWER,FLOW,ROLE,ROPE,FORE,FOE,OWL", "CANDLE,CLEAN,LANCE,DANCE,LANE,LAND,DEAL,CAN", "BUTTER,TUBER,BRUTE,TUBE,TRUE,BLUE,RUB,BE", "WONDER,DOWNER,OWNER,DOWN,WORD,WORE,RODE,ONE", "MARBLE,BLAME,AMBLE,REALM,BEAM,LAMB,BARE,ARM", "FRIEND,FINDER,FINED,FIRE,FIND,RIDE,DINE,RED", "CLOUD,COULD,COLD,LOUD,DUO,COD,OLD,COOL", "SQUARE,QUA,USE,EAR,ARE,SEA,SURE,USER", "WINTER,WRITE,TWINE,TIRE,WIRE,TWIN,NEW,WET", "FOREST,FORTE,STORE,ROSE,SOFT,REST,TOES,ORE"].map(x=>x.split(","));

function wordsGame({host,run,rng}:Context):Game {
  const bank = picked(WORD_BANKS,rng), words=shuffle(bank.slice(0,Math.min(bank.length,run.size+1)),rng).slice(0,run.size);
  const inventory=new Map<string,number>();for(const word of words){const count=new Map<string,number>();for(const char of word)count.set(char,(count.get(char)||0)+1);for(const [char,n] of count)inventory.set(char,Math.max(inventory.get(char)||0,n));}
  const letters=shuffle([...inventory].flatMap(([char,n])=>Array(n).fill(char) as string[]),rng), placed:{word:string;x:number;y:number;vertical:boolean}[]=[];
  const cells=new Map<string,string>();
  function canPlace(word:string,x:number,y:number,vertical:boolean){for(let i=0;i<word.length;i++){const xx=x+(vertical?0:i), yy=y+(vertical?i:0);if(xx<0||yy<0||xx>=18||yy>=18)return false;const old=cells.get(`${xx},${yy}`);if(old&&old!==word[i])return false;}return true;}
  function place(word:string,x:number,y:number,vertical:boolean){placed.push({word,x,y,vertical});for(let i=0;i<word.length;i++)cells.set(`${x+(vertical?0:i)},${y+(vertical?i:0)}`,word[i]);}
  place(words[0],5,6,false);
  for(const word of words.slice(1)) {let done=false;for(const [loc,letter] of shuffle([...cells],rng)){const [cx,cy]=loc.split(",").map(Number);for(let at=0;at<word.length;at++){if(word[at]!==letter)continue;for(const vertical of [true,false]){const x=cx-(vertical?0:at),y=cy-(vertical?at:0);if(canPlace(word,x,y,vertical)){place(word,x,y,vertical);done=true;break;}}if(done)break;}if(done)break;}if(!done){const y=9+placed.length;if(canPlace(word,2,y,false))place(word,2,y,false);}}
  const found=new Set<string>(), revealed=new Set<string>(); let entry="", score=0, state:State="playing", message="Build words using the letter wheel.";
  let selected:number[]=[];
  function submit(){const match=words.find(w=>w===entry&&!found.has(w));if(match){found.add(match);score+=match.length*50;message=`${match} found.`;if(found.size===words.length){state="won";message="Crossword complete!";}}else message=entry?"That word is not on this board.":"Select letters first.";entry="";selected=[];}
  const game:Game={get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${found.size}/${words.length} words`},get canHelp(){return found.size<words.length},
    render(){const coords=[...cells.keys()].map(k=>k.split(",").map(Number));const x0=Math.min(...coords.map(c=>c[0])),x1=Math.max(...coords.map(c=>c[0])),y0=Math.min(...coords.map(c=>c[1])),y1=Math.max(...coords.map(c=>c[1]));let html="";for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const value=cells.get(`${x},${y}`);const visible=placed.some(p=>found.has(p.word)&&Array.from({length:p.word.length},(_,i)=>`${p.x+(p.vertical?0:i)},${p.y+(p.vertical?i:0)}`).includes(`${x},${y}`))||revealed.has(`${x},${y}`);html+=`<span class="x-word-cell ${!value?"empty":visible?"filled":""}">${value&&visible?value:""}</span>`;}host.innerHTML=`<div class="x-panel"><div class="x-word-grid" style="grid-template-columns:repeat(${x1-x0+1},40px)">${html}</div><div class="x-row">${letters.map((letter,i)=>`<button class="x-letter ${selected.includes(i)?"used":""}" data-letter="${i}">${letter}</button>`).join("")}</div><div class="x-row"><strong class="x-chip">${entry||"Choose letters"}</strong><button class="x-action" data-word-submit>Submit</button><button class="x-action" data-word-clear>Clear</button></div><span class="x-help">${words.map(w=>found.has(w)?w:"_ ".repeat(w.length)).join(" · ")}</span></div>`;},
    key(k){if(k==="enter")submit();else if(k==="backspace"){selected.pop();entry=selected.map(i=>letters[i]).join("");}else if(/^[a-z]$/.test(k)){const i=letters.findIndex((v,j)=>v===k.toUpperCase()&&!selected.includes(j));if(i>=0){selected.push(i);entry+=letters[i];}}},
    click(e){const i=eventIndex(e,"letter");if(i>=0&&!selected.includes(i)){selected.push(i);entry+=letters[i];}if((e.target as HTMLElement).closest("[data-word-submit]"))submit();if((e.target as HTMLElement).closest("[data-word-clear]")){entry="";selected=[];}},tick(){},lifeline(){const p=placed.find(p=>!found.has(p.word));if(p){const i=Math.floor(rng()*p.word.length);revealed.add(`${p.x+(p.vertical?0:i)},${p.y+(p.vertical?i:0)}`);message="One crossword letter was revealed.";}}
  };return game;
}

const LINES=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
function ticGame({host,run,rng}:Context):Game {const board=Array(9).fill("") as string[];let selected=4,score=0,state:State="playing",message="You are X. Make three in a row.",blocked=-1;
  const outcome=(b:string[])=>{for(const line of LINES){const [a,c,d]=line;if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];}return b.every((v,i)=>Boolean(v)||i===blocked)?"draw":"";};
  function minimax(b:string[],turn:string,depth:number):number{const result=outcome(b);if(result)return result==="O"?10-depth:result==="X"?depth-10:0;const values=[];for(let i=0;i<9;i++)if(!b[i]&&i!==blocked){b[i]=turn;values.push(minimax(b,turn==="O"?"X":"O",depth+1));b[i]="";}return turn==="O"?Math.max(...values):Math.min(...values);}
  function move(i:number){if(i<0||i>8||board[i]||i===blocked)return;board[i]="X";score+=10;let result=outcome(board);if(result){finish(result);return;}const open=board.map((v,j)=>!v&&j!==blocked?j:-1).filter(j=>j>=0);if(!open.length){finish("draw");return;}let choice=picked(open,rng);if(diff(run)>=1){for(const mark of ["O","X"]){const winning=open.find(j=>{board[j]=mark;const yes=outcome(board)===mark;board[j]="";return yes;});if(winning!==undefined){choice=winning;break;}}}if(diff(run)>=2){let best=-Infinity;for(const j of open){board[j]="O";const value=minimax(board,"X",0);board[j]="";if(value>best){best=value;choice=j;}}if(rng()<.14)choice=picked(open,rng);}board[choice]="O";result=outcome(board);if(result)finish(result);else message="Your turn.";}
  function finish(result:string){if(result==="X"){state="won";score+=300;message="Three in a row!";}else{state="lost";message=result==="draw"?"Draw. Restart for another try.":"Computer won. Restart to try again.";}}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${board.filter(Boolean).length}/9 squares`},get canHelp(){return blocked<0},render(){host.innerHTML=`<div class="x-board" style="grid-template-columns:repeat(3,1fr);max-width:360px">${board.map((v,i)=>`<button class="x-tile ${i===selected?"selected":""}" style="height:100px;font-size:52px;color:${v==="X"?"#5c9ea0":"#c58275"}" data-square="${i}">${v|| (i===blocked?"✦":"")}</button>`).join("")}</div>`;},key(k){if(k==="arrowleft")selected=(selected+8)%9;else if(k==="arrowright")selected=(selected+1)%9;else if(k==="arrowup")selected=(selected+6)%9;else if(k==="arrowdown")selected=(selected+3)%9;else if(k==="enter"||k===" ")move(selected);},click(e){move(eventIndex(e,"square"));},tick(){},lifeline(){const open=board.map((v,i)=>!v?i:-1).filter(i=>i>=0);if(open.length){blocked=picked(open,rng);message="The computer cannot use the marked square.";}}};
}

function slideGame({host,run,rng}:Context):Game {const n=run.size,total=n*n,board=Array.from({length:total},(_,i)=>(i+1)%total);let gap=total-1,score=0,moves=0,state:State="playing",message="Move a tile next to the empty space.";const history:number[]=[];
  const adjacent=(a:number,b:number)=>Math.abs(Math.floor(a/n)-Math.floor(b/n))+Math.abs(a%n-b%n)===1;
  function swap(i:number,record=true){if(!adjacent(i,gap))return false;[board[i],board[gap]]=[board[gap],board[i]];if(record){history.push(gap);moves++;score=Math.max(0,1000-moves*5);if(board.every((v,j)=>v===(j+1)%total)){state="won";score+=n*300;message="Puzzle solved!";}}gap=i;return true;}
  for(let i=0;i<total*(12+diff(run)*8)+run.level%17;i++){const opts=[gap-n,gap+n,gap-1,gap+1].filter(j=>j>=0&&j<total&&adjacent(j,gap)&&j!==history.at(-1));const choice=picked(opts.length?opts:[gap-n,gap+n,gap-1,gap+1].filter(j=>j>=0&&j<total&&adjacent(j,gap)),rng);history.push(gap);swap(choice,false);}history.length=0;
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${moves} moves · ${n} × ${n}`},render(){host.innerHTML=`<div class="x-board" style="grid-template-columns:repeat(${n},1fr);max-width:${Math.min(550,n*100)}px">${board.map((v,i)=>`<button class="x-tile" data-slide="${i}" style="aspect-ratio:1;font-size:${n===5?22:30}px;${v===0?"visibility:hidden":""}">${v||""}</button>`).join("")}</div>`;},key(k){const options:Record<string,number>={arrowup:gap+n,arrowdown:gap-n,arrowleft:gap+1,arrowright:gap-1};if(options[k]!==undefined)swap(options[k]);},click(e){swap(eventIndex(e,"slide"));},tick(){},lifeline(){const target=Array.from({length:total},(_,i)=>i).find(i=>board[i]!==((i+1)%total)&&adjacent(i,gap));if(target!==undefined){swap(target);message="One tile moved for you.";}else message="No useful tile is next to the gap.";}};
}

function mathGame({host,run,rng}:Context):Game {let index=0,score=0,mistakes=0,state:State="playing",message="Choose the correct answer.",question="",answer=0,choices:number[]=[],removed:number[]=[];
  function next(){const d=diff(run),max=[15,40,99][d]+Math.min(100,run.level*2),a=1+Math.floor(rng()*max),b=1+Math.floor(rng()*max),op=picked(d===0?["+","-","×"]:["+","-","×","÷"],rng);if(op==="+"){answer=a+b;question=`${a} + ${b}`;}else if(op==="-"){answer=Math.max(a,b)-Math.min(a,b);question=`${Math.max(a,b)} − ${Math.min(a,b)}`;}else if(op==="×"){const x=1+a%12,y=1+b%12;answer=x*y;question=`${x} × ${y}`;}else{const x=1+a%12,y=1+b%12;answer=x;question=`${x*y} ÷ ${y}`;}const wrong=new Set<number>();while(wrong.size<3){const value=answer+(Math.floor(rng()*13)-6)*(1+Math.floor(answer/30));if(value>=0&&value!==answer)wrong.add(value);}choices=shuffle([answer,...wrong],rng);removed=[];}
  next();function choose(i:number){if(i<0||i>3||removed.includes(i))return;if(choices[i]===answer){index++;score+=100+Math.max(0,30-mistakes*10);message="Correct.";if(index>=run.size){state="won";message="Quiz complete!";}else next();}else{mistakes++;message=`Not quite. ${3-mistakes} tries remain.`;if(mistakes>=3){state="lost";message="Three mistakes. Restart this quiz.";}}}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${index}/${run.size} answered · ${3-mistakes} lives`},render(){host.innerHTML=`<div class="x-panel"><span class="x-stats">QUESTION ${index+1}</span><h3 style="font-size:42px;margin:20px">${question} = ?</h3><div class="x-board" style="grid-template-columns:repeat(2,1fr);max-width:400px">${choices.map((v,i)=>`<button class="x-tile" data-answer="${i}" ${removed.includes(i)?"disabled":""}>${removed.includes(i)?"—":v}</button>`).join("")}</div></div>`;},key(k){if(/[1-4]/.test(k))choose(Number(k)-1);},click(e){choose(eventIndex(e,"answer"));},tick(){},lifeline(){removed=choices.map((v,i)=>v!==answer?i:-1).filter(i=>i>=0).slice(0,2);message="Two incorrect choices removed.";}};
}

function ladderGame({host,run,rng}:Context):Game {const jumps=new Map<number,number>();const occupied=new Set<number>();for(let i=0;i<11+diff(run)*3;i++){let a=2+Math.floor(rng()*90),b=2+Math.floor(rng()*90);if(Math.abs(a-b)<12||occupied.has(a)||occupied.has(b))continue;occupied.add(a);occupied.add(b);jumps.set(a,b);}let positions=[1,1],turns=0,score=0,state:State="playing",message="Roll to begin the race.",lastRoll=0,reroll=false;
  function advance(player:number,roll:number){const from=positions[player];if(from+roll<=100)positions[player]=from+roll;const land=jumps.get(positions[player]);if(land)positions[player]=land;message=`${player===0?"You":"Computer"} rolled ${roll}${land?land>from?" and climbed!":" and slid!":"."}`;if(positions[player]===100){state=player===0?"won":"lost";message=player===0?"You reached square 100!":"Computer reached square 100. Restart to retry.";if(player===0)score+=1000;}}
  function roll(){if(state!=="playing")return;const value=reroll?6:1+Math.floor(Math.random()*6);reroll=false;lastRoll=value;turns++;advance(0,value);score=Math.max(0,1000-turns*8);if(state==="playing"){const cv=1+Math.floor(Math.random()*6);advance(1,cv);} }
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `You ${positions[0]} · Rival ${positions[1]} · Last roll ${lastRoll||"—"}`},render(){host.innerHTML=`<div class="x-panel"><div class="x-board" style="grid-template-columns:repeat(10,1fr);gap:2px;max-width:550px">${Array.from({length:100},(_,i)=>{const row=Math.floor(i/10),col=i%10,num=100-row*10-(row%2?9-col:col),jump=jumps.get(num);return `<span class="x-grid-cell" style="font-size:12px;${jump?`background:${jump>num?"#d3e8d7":"#f0dbd3"}`:""}">${positions[0]===num?"🔵":positions[1]===num?"🔴":jump?jump>num?"↗":"↘":num}</span>`;}).join("")}</div><div class="x-row"><button class="x-action" data-roll>Roll die</button><strong class="x-chip">${lastRoll||"–"}</strong></div></div>`;},key(k){if(k===" "||k==="enter")roll();},click(e){if((e.target as HTMLElement).closest("[data-roll]"))roll();},tick(){},lifeline(){reroll=true;message="Your next roll is a six.";}};
}

function ludoGame({host,run,rng}:Context):Game {const rivals=1+diff(run),tokens=Array.from({length:rivals+1},()=>[-1,-1,-1,-1]),starts=[0,13,26,39],safe=new Set([0,8,13,21,26,34,39,47]);let roll=0,turns=0,score=0,state:State="playing",message="Roll a six to enter the track.";
  function legal(player:number,value:number){return tokens[player].map((p,i)=>p===-1?value===6?i:-1:p+value<=57?i:-1).filter(i=>i>=0);}
  function move(player:number,i:number,value:number){let p=tokens[player][i];p=p===-1?0:p+value;tokens[player][i]=p;if(p<52){const tile=(starts[player]+p)%52;if(!safe.has(tile))for(let other=0;other<tokens.length;other++)if(other!==player)for(let j=0;j<4;j++)if(tokens[other][j]>=0&&tokens[other][j]<52&&(starts[other]+tokens[other][j])%52===tile){tokens[other][j]=-1;message="A token was captured!";}}if(tokens[player].every(v=>v===57)){state=player===0?"won":"lost";message=player===0?"All four tokens are home!":"A rival brought all tokens home.";} }
  function rivalTurns(){for(let player=1;player<tokens.length&&state==="playing";player++){const value=1+Math.floor(Math.random()*6),choices=legal(player,value);if(choices.length){const i=choices.sort((a,b)=>tokens[player][b]-tokens[player][a])[0];move(player,i,value);}}}
  function throwDie(){if(roll)return;roll=1+Math.floor(Math.random()*6);turns++;if(!legal(0,roll).length){message=`Rolled ${roll}. No legal token; rival plays.`;roll=0;rivalTurns();}else message=`Rolled ${roll}. Choose a highlighted token.`;}
  function choose(i:number){if(!roll||!legal(0,roll).includes(i))return;move(0,i,roll);score=tokens[0].reduce((s,p)=>s+Math.max(0,p+1)*5,0);roll=0;if(state==="playing")rivalTurns();}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${tokens[0].filter(p=>p===57).length}/4 home · Roll ${roll||"—"}`},render(){const colors=["#5a9caf","#d38378","#c7a85e","#9b84b8"];host.innerHTML=`<div class="x-panel"><div class="x-board" style="grid-template-columns:repeat(13,1fr);max-width:600px;gap:2px">${Array.from({length:52},(_,tile)=>`<span class="x-grid-cell" style="background:${safe.has(tile)?"#d9e8dd":"#eef2e9"};font-size:11px">${tokens.flatMap((group,p)=>group.map((pos,i)=>({p,i,pos}))).filter(t=>t.pos>=0&&t.pos<52&&(starts[t.p]+t.pos)%52===tile).map(t=>`<b class="x-token" style="background:${colors[t.p]}">${t.p===0?"●":""}</b>`).join("")||tile+1}</span>`).join("")}</div><div class="x-row">${tokens.map((group,p)=>`<span class="x-chip" style="border:2px solid ${colors[p]}">${p===0?"You":`Rival ${p}`} ${group.filter(v=>v===57).length}/4</span>`).join("")}</div><div class="x-row">${tokens[0].map((p,i)=>`<button class="x-action" data-ludo="${i}" ${!roll||!legal(0,roll).includes(i)?"disabled":""}>Token ${i+1} · ${p<0?"Base":p===57?"Home":p}</button>`).join("")}</div><button class="x-action" data-ludo-roll ${roll?"disabled":""}>Roll die</button><strong class="x-chip">${roll||"–"}</strong></div>`;},key(k){if(k===" "||k==="enter")throwDie();if(/[1-4]/.test(k))choose(Number(k)-1);},click(e){if((e.target as HTMLElement).closest("[data-ludo-roll]"))throwDie();const i=eventIndex(e,"ludo");if(i>=0)choose(i);},tick(){},lifeline(){roll=6;message="Choose a token with your guaranteed six.";}};
}

function chessGame({host,run,rng}:Context):Game {const chess=new Chess();let selected="",cursor=52,score=0,state:State="playing",message="White moves first.";
  const glyph:Record<string,string>={wk:"♔",wq:"♕",wr:"♖",wb:"♗",wn:"♘",wp:"♙",bk:"♚",bq:"♛",br:"♜",bb:"♝",bn:"♞",bp:"♟"};
  const square=(i:number)=>`${"abcdefgh"[i%8]}${8-Math.floor(i/8)}`;
  function move(to:string){if(state!=="playing")return;const piece=chess.get(to as any);if(!selected){if(piece?.color==="w")selected=to;return;}if(piece?.color==="w"){selected=to;return;}try{const made=chess.move({from:selected,to,promotion:"q"});selected="";if(made){score+=made.captured?100:10;if(chess.isCheckmate()){state="won";message="Checkmate!";score+=1500;return;}if(chess.isDraw()){state="lost";message="Draw. Restart to try for a win.";return;}computer();}}catch{message="Illegal move. Choose another square.";}}
  function computer(){const choices=chess.moves({verbose:true});if(!choices.length){state=chess.isCheckmate()?"won":"lost";return;}let best=-Infinity,move=choices[0];for(const item of shuffle(choices,rng)){let value=(item.captured?{p:1,n:3,b:3,r:5,q:9}[item.captured]||0:0)*10+(item.san.includes("+")?3:0)+rng()*[10,3,1][diff(run)];if(diff(run)>0){chess.move(item);const replies=chess.moves({verbose:true});value-=Math.max(0,...replies.map(r=>r.captured?({p:1,n:3,b:3,r:5,q:9}[r.captured]||0)*5:0));chess.undo();}if(value>best){best=value;move=item;}}chess.move(move);if(chess.isCheckmate()){state="lost";message="Checkmate. Restart to try again.";}else if(chess.isDraw()){state="lost";message="Draw. Restart to try for a win.";}else message=chess.isCheck()?"Check! Protect your king.":`Computer played ${move.san}.`;}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${chess.moveNumber()}. ${chess.isCheck()?"Check · ":""}White to move`},render(){const board=chess.board();host.innerHTML=`<div class="x-board" style="grid-template-columns:repeat(8,1fr);max-width:560px;gap:0;border:8px solid #687e75;border-radius:8px;overflow:hidden">${board.flatMap((row,r)=>row.map((piece,c)=>{const sq=square(r*8+c),legal=selected&&chess.moves({square:selected as any,verbose:true}).some(m=>m.to===sq);return `<button data-chess="${r*8+c}" style="aspect-ratio:1;border:0;background:${selected===sq?"#eddb9e":legal?"#b7d8c1":(r+c)%2?"#8daca0":"#f3efe3"};color:${piece?.color==="w"?"#fffdf2":"#263c3b"};text-shadow:0 1px 2px #354239;font-size:clamp(24px,5vw,48px);cursor:pointer">${piece?glyph[piece.color+piece.type]:""}</button>`;})).join("")}</div><p class="x-help">${chess.history().slice(-6).join(" · ")}</p>`;},key(k){if(k==="arrowleft")cursor=(cursor+63)%64;else if(k==="arrowright")cursor=(cursor+1)%64;else if(k==="arrowup")cursor=(cursor+56)%64;else if(k==="arrowdown")cursor=(cursor+8)%64;else if(k==="enter")move(square(cursor));},click(e){const i=eventIndex(e,"chess");if(i>=0){cursor=i;move(square(i));message=selected?`Selected ${selected}. Choose a destination.`:message;}},tick(){},lifeline(){const candidates=chess.moves({verbose:true});const safer=candidates.find(m=>{chess.move(m);const threatened=chess.isCheck();chess.undo();return !threatened;});if(safer){move(safer.from);move(safer.to);message="A legal move was played for you.";}}};
}

function linkGame({host,run,rng}:Context):Game {const n=run.size,colors=["#df887b","#7ab7cf","#e4c06e","#9bc797","#b89acb","#d69cb6","#8fc7bc","#c2ad83","#9daee0"];const endpoints=new Map<number,number>();const solution:number[][]=[];
  // Partition the board into serpentine strips. Each strip is a valid complete path.
  const bands:number[][]=[];for(let y=0;y<n;){const width=y+1<n&&rng()<.65?2:1,rows=width===2?[y,y+1]:[y],path:number[]=[];for(let r=0;r<rows.length;r++){const yy=rows[r],xs=Array.from({length:n},(_,x)=>r%2? n-1-x:x);for(const x of xs)path.push(yy*n+x);}bands.push(path);y+=width;}const perm=shuffle(bands,rng);for(let i=0;i<perm.length;i++){const path=perm[i];if(rng()<.5)path.reverse();solution.push(path);endpoints.set(path[0],i);endpoints.set(path.at(-1)!,i);}const paths=solution.map(path=>[path[0]]);let active=-1,score=0,state:State="playing",message="Connect matching endpoints and cover the board.";
  const neighbor=(a:number,b:number)=>Math.abs(Math.floor(a/n)-Math.floor(b/n))+Math.abs(a%n-b%n)===1;
  function add(cell:number){if(cell<0||cell>=n*n)return;const ep=endpoints.get(cell);if(ep!==undefined&&active<0){active=ep;paths[ep]=[cell];return;}if(active<0)return;const path=paths[active],prev=path.at(-1)!;if(cell===prev)return;if(path.length>1&&cell===path.at(-2)){path.pop();return;}if(!neighbor(prev,cell))return;if(ep!==undefined&&ep!==active)return;if(paths.some((p,i)=>i!==active&&p.includes(cell)))return;if(path.includes(cell))return;path.push(cell);if(ep===active&&cell!==path[0])active=-1;const full=paths.every((p,i)=>p.length>1&&endpoints.get(p[0])===i&&endpoints.get(p.at(-1)!)===i)&&new Set(paths.flat()).size===n*n;if(full){state="won";score=1000+n*n*10;message="Every link fits!";}else score=new Set(paths.flat()).size*10;}
  return {get score(){return score},get state(){return state},set state(v){state=v},get message(){return message},get progress(){return `${new Set(paths.flat()).size}/${n*n} cells filled`},render(){host.innerHTML=`<div class="x-board" style="grid-template-columns:repeat(${n},1fr);max-width:560px">${Array.from({length:n*n},(_,i)=>{const color=paths.findIndex(p=>p.includes(i)),end=endpoints.get(i);return `<button class="x-grid-cell ${color>=0?"path":""} ${end!==undefined?"endpoint":""}" data-link="${i}" style="--path-color:${color>=0?colors[color]:"#edf3ef"};min-height:42px">${end!==undefined?`<span class="x-token" style="background:${colors[end]}"></span>`:""}</button>`;}).join("")}</div>`;},key(){},click(e){add(eventIndex(e,"link"));},move(e){if(e.buttons===1){const i=eventIndex(e,"link");if(i>=0)add(i);}},tick(){},lifeline(){const incomplete=paths.findIndex((p,i)=>p.length<solution[i].length);if(incomplete>=0){paths[incomplete]=[...solution[incomplete]];active=-1;score=new Set(paths.flat()).size*10;message="One full connection was drawn.";if(new Set(paths.flat()).size===n*n){state="won";message="Every link fits!";}}}};
}

export const puzzleFactories:Record<string,(ctx:Context)=>Game>={"words-of-wonder":wordsGame,"tic-tac-toe":ticGame,"slide-puzzle":slideGame,"math-quiz":mathGame,"snake-ladder":ladderGame,ludo:ludoGame,chess:chessGame,link:linkGame};
