import Phaser from "phaser";
import type { GameInfo } from "../../data/games";

import type { Difficulty } from "./types";
export type { Difficulty } from "./types";
type Bits = Record<string, Phaser.Input.Keyboard.Key>;
const W = 900, H = 560;
const ink = 0x22272a, paper = 0xe9e4d8, green = 0x8caa83, gold = 0xe1b86b, red = 0xc96f5e, blue = 0x739ca7;
const patternBags = new Map<string, number[]>();
function patternSeed(id: string) {
  let bag = patternBags.get(id) ?? [];
  if (!bag.length) { bag = Array.from({ length: 256 }, (_, i) => i + 1); for (let i = bag.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [bag[i], bag[j]] = [bag[j], bag[i]]; } }
  patternBags.set(id, bag); return bag.pop()!;
}
function rng(seed: number) { let state = (seed >>> 0) || 1; return () => { state += 0x6D2B79F5; let t = state; t = Math.imul(t ^ t >>> 15, t | 1); t ^= t + Math.imul(t ^ t >>> 7, t | 61); return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
function makeMaze(seed: number, cols = 17, rows = 11) {
  const random = rng(seed); const grid = Array.from({ length: rows }, () => Array(cols).fill(1));
  const stack: [number, number][] = [[1, 1]]; grid[1][1] = 0;
  while (stack.length) { const [x,y] = stack.at(-1)!; const dirs: [number,number][] = ([[2,0],[-2,0],[0,2],[0,-2]] as [number,number][]).filter(([dx,dy]) => grid[y+dy]?.[x+dx] === 1); if (!dirs.length) { stack.pop(); continue; } const [dx,dy] = dirs[Math.floor(random()*dirs.length)]; grid[y+dy/2][x+dx/2] = 0; grid[y+dy][x+dx] = 0; stack.push([x+dx,y+dy]); }
  // Add a seed-dependent number of loops so routes have varied risk/reward choices.
  for (let i=0, n=7+Math.floor(random()*15); i<n; i++) { const x=1+Math.floor(random()*(cols-2)), y=1+Math.floor(random()*(rows-2)); if (grid[y][x] && ((grid[y-1][x]===0&&grid[y+1][x]===0)||(grid[y][x-1]===0&&grid[y][x+1]===0))) grid[y][x]=0; }
  return grid;
}

class CasualScene extends Phaser.Scene {
  static bootData: { gameInfo: GameInfo; difficulty: Difficulty; seed: number } | null = null;
  private gameInfo!: GameInfo; private difficulty!: Difficulty; private seed = 1; private random = rng(1); private g!: Phaser.GameObjects.Graphics; private hud!: Phaser.GameObjects.Text; private keys!: Bits;
  private score = 0; private lives = 3; private over = false; private elapsed = 0; private x = 0; private y = 0; private paddleX = W/2; private vx = 0; private vy = 0; private cells: number[][] = []; private revealed: boolean[][] = []; private flags: boolean[][] = []; private matches: boolean[] = []; private chosen: number[] = []; private entities: { x:number;y:number;kind:number;alive:boolean;timer:number }[] = []; private maze: number[][] = []; private tile = 32; private phase = 0; private combo = 0; private target = 0; private held = false; private question = ""; private message = ""; private livesText = ""; private word = ""; private guessed = new Set<string>(); private wrong = 0; private quizIndex = 0; private quizAnswer = 0; private quizOptions: number[] = []; private quizTextOptions: string[] = []; private labels: Phaser.GameObjects.Text[] = []; private labelCursor = 0;
  constructor() { super("casual-scene"); }
  init(data?: { gameInfo: GameInfo; difficulty: Difficulty; seed: number }) { const launch=data?.gameInfo?data:CasualScene.bootData!; this.gameInfo=launch.gameInfo; this.difficulty=launch.difficulty; this.seed=launch.seed; this.random=rng(launch.seed); }
  create() {
    this.labels=[]; this.labelCursor=0;
    this.g=this.add.graphics(); this.hud=this.add.text(25,18,"",{fontFamily:"Arial, sans-serif",fontSize:"18px",color:"#22272a",fontStyle:"bold"});
    this.keys=this.input.keyboard!.addKeys("UP,DOWN,LEFT,RIGHT,W,A,S,D,SPACE,ENTER") as Bits;
    this.input.on("pointerdown",(p: Phaser.Input.Pointer)=>this.click(p.x,p.y));
    this.startMode();
  }
  private label(x:number,y:number,text:string,style:Phaser.Types.GameObjects.Text.TextStyle={}) { const i=this.labelCursor++; let obj=this.labels[i]; if(!obj){obj=this.add.text(x,y,text,style);this.labels[i]=obj;}else{obj.setPosition(x,y).setText(text).setStyle(style).setVisible(true);} return obj; }
  private startMode() {
    const id=this.gameInfo.id, r=this.random;
    this.score=0; this.lives=3; this.elapsed=0; this.over=false; this.phase=0; this.combo=0; this.entities=[]; this.cells=[]; this.maze=[]; this.chosen=[]; this.message=""; this.held=false;
    if (["minesweeper"].includes(id)) this.makeMines();
    if (["memory-match"].includes(id)) this.makeCards();
    if(id==="nuts-and-bolts"){const colors=Array.from({length:4},(_,color)=>Array(4).fill(color)).flat();for(let i=colors.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[colors[i],colors[j]]=[colors[j],colors[i]];}this.cells=[colors.slice(0,4),colors.slice(4,8),colors.slice(8,12),colors.slice(12),[]];}
    if(id==="circuit-break"){this.cells=Array.from({length:7},()=>Array.from({length:7},()=>Math.floor(r()*4)));this.cells[3][0]=1;this.cells[3][6]=1;}
    if(id==="hangman"){const words=["GARDEN","PLANET","PUZZLE","SUNSET","POCKET","JOURNEY","MARKET","HARBOR","THUNDER","COMPASS","ORCHARD","LANTERN"];this.word=words[Math.floor(r()*words.length)];this.guessed.clear();this.wrong=0;}
    if(id==="math-test"){this.quizIndex=0;this.makeMath();}
    if(id==="microsoft-trivia"){const trivia=[["Which company makes Windows?","Microsoft","Apple","Sony","Nintendo"],["Which app is commonly used for spreadsheets?","Excel","Paint","Notepad","Photos"],["What is the name of Microsoft's game console?","Xbox","Switch","PlayStation","Atari"],["Which service stores files online?","OneDrive","Bing","Teams","Edge"]];const q=trivia[Math.floor(r()*trivia.length)];this.question=q[0];this.quizAnswer=0;this.quizOptions=[0,1,2,3];this.quizTextOptions=q.slice(1);}
    if (["2048"].includes(id)) { this.cells=Array.from({length:4},()=>Array(4).fill(0)); this.spawn2048(); this.spawn2048(); }
    if (["snake","snake-arena"].includes(id)) { this.entities=[{x:7,y:7,kind:0,alive:true,timer:0},{x:6,y:7,kind:0,alive:true,timer:0},{x:5,y:7,kind:0,alive:true,timer:0}]; this.spawnEntity(1); }
    if (id.includes("maze")||id==="ghost-maze"||id==="treasure-escape"||id==="robot-hunt"||id==="rising-lava"||id==="shadow-chase") { this.maze=makeMaze(this.seed); this.tile=Math.min(38,Math.floor(Math.min((W-70)/this.maze[0].length,(H-100)/this.maze.length))); this.x=1;this.y=1;this.entities=[]; const count=id==="ghost-maze"?3+Math.floor(r()*8):id==="robot-hunt"?2: id==="treasure-escape"?2:1; for(let i=0;i<count;i++) this.entities.push({x:this.maze[0].length-2-i%2,y:this.maze.length-2,kind:i,alive:true,timer:0}); }
    if (["bubble-pop"].includes(id)) { for(let y=0;y<6;y++) for(let x=0;x<13;x++) this.entities.push({x,y,kind:Math.floor(r()*5),alive:true,timer:0}); this.target=Math.floor(r()*5); }
    if (["tower-defense"].includes(id)) { for(let i=0;i<7;i++) this.entities.push({x:-i*65,y:165+Math.floor(r()*205),kind:1,alive:true,timer:0}); }
    if (["brick-breaker"].includes(id)) { this.x=W/2;this.y=H-65;this.paddleX=W/2;this.vx=3;this.vy=-4; for(let y=0;y<5;y++)for(let x=0;x<12;x++)if(r()>.08)this.entities.push({x:80+x*62,y:90+y*31,kind:Math.floor(r()*4),alive:true,timer:0}); }
    if (["space-shooter","action-arena","toon-toss","archery","fishing-frenzy"].includes(id)) { this.x=W/2;this.y=H-80; if(id==="space-shooter"||id==="action-arena") for(let i=0;i<5;i++)this.spawnEntity(2); }
    if (id==="pixel-platformer"||id==="rising-lava") { this.x=80;this.y=H-110; for(let i=0;i<12;i++)this.entities.push({x:90+i*61+Math.floor(r()*26),y:H-70-Math.floor(r()*170),kind:i%3===0?2:0,alive:true,timer:0}); }
    if (["whack-a-mole"].includes(id)) { this.phase=0; this.spawnEntity(3); }
    if (id==="color-hunter") { this.target=Math.floor(r()*5); for(let i=0;i<18;i++)this.spawnEntity(Math.floor(r()*5)); }
    if (id==="fishing-frenzy") this.phase=0;
    if (id==="ghost-maze"||id==="treasure-escape"||id==="robot-hunt"||id==="rising-lava"||id==="shadow-chase"||id==="bomb-maze"||id==="escape-the-maze"||id==="infinite-maze") this.spawnEntity(id==="treasure-escape"?4: id==="robot-hunt"?5: id==="rising-lava"?6: id==="bomb-maze"?7: 8);
    if (id==="bomb-maze") { this.maze=makeMaze(this.seed); for(let y=1;y<this.maze.length-1;y++)for(let x=1;x<this.maze[0].length-1;x++)if(!this.maze[y][x]&&this.random()>.86)this.maze[y][x]=2; }
    if(this.maze.length&&["ghost-maze","maze-chase","treasure-escape","robot-hunt","escape-the-maze"].includes(id)){const count=id==="escape-the-maze"?3:id==="treasure-escape"?16:18;for(let i=0;i<count;i++){let x=1,y=1;for(let tries=0;tries<40&&(this.maze[y][x]!==0||(x===1&&y===1));tries++){x=1+Math.floor(r()*(this.maze[0].length-2));y=1+Math.floor(r()*(this.maze.length-2));}if(this.maze[y][x]===0)this.maze[y][x]=3;}}
    this.input.keyboard!.on("keydown",this.keyDown,this);
    this.draw();
  }
  private makeMines(){ const n=this.difficulty==="easy"?9:this.difficulty==="medium"?11:13, mines=this.difficulty==="easy"?10:this.difficulty==="medium"?18:28; this.cells=Array.from({length:n},()=>Array(n).fill(0));this.revealed=Array.from({length:n},()=>Array(n).fill(false));this.flags=Array.from({length:n},()=>Array(n).fill(false));let put=0;while(put<mines){const x=Math.floor(this.random()*n),y=Math.floor(this.random()*n);if(!this.cells[y][x]){this.cells[y][x]=-1;put++;}} for(let y=0;y<n;y++)for(let x=0;x<n;x++)if(this.cells[y][x]!==-1)this.cells[y][x]=this.neighbors(x,y).filter(([a,b])=>this.cells[b][a]===-1).length; }
  private neighbors(x:number,y:number){return [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]].map(([dx,dy])=>[x+dx,y+dy] as [number,number]).filter(([a,b])=>this.cells[b]?.[a]!==undefined);}
  private makeCards(){const total=16, vals=Array.from({length:total/2},(_,i)=>i);this.matches=Array(total).fill(false);for(let i=vals.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[vals[i],vals[j]]=[vals[j],vals[i]];}const deck=[...vals,...vals];for(let i=deck.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}this.cells=[deck];}
  private spawn2048(){const empty: [number,number][]=[];for(let y=0;y<4;y++)for(let x=0;x<4;x++)if(!this.cells[y][x])empty.push([x,y]);if(empty.length){const [x,y]=empty[Math.floor(this.random()*empty.length)];this.cells[y][x]=this.random()<.9?2:4;}}
  private spawnEntity(kind:number){const x=40+this.random()*(W-80),y=80+this.random()*(H-160);this.entities.push({x,y,kind,alive:true,timer:0});}
  private keyDown(e: KeyboardEvent){ if(this.over){if(e.key==="Enter")this.scene.restart({gameInfo:this.gameInfo,difficulty:this.difficulty,seed:patternSeed(this.gameInfo.id)});return;} const id=this.gameInfo.id; if(id==="hangman"&&/^[a-z]$/i.test(e.key)){this.guess(e.key.toUpperCase());return;} if((id==="math-test"||id==="microsoft-trivia")&&/^[1-4]$/.test(e.key)){this.answerQuiz(Number(e.key)-1);return;} if(this.maze.length&&e.key.startsWith("Arrow")){const d:{[key:string]:[number,number]}={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};const [dx,dy]=d[e.key]??[0,0];this.stepMaze(this.x+dx,this.y+dy);this.draw();return;} if(id==="2048"){if(["ArrowUp","ArrowDown","ArrowLeft","ArrowRight"].includes(e.key))this.move2048(e.key);return;} if(["snake","snake-arena"].includes(id)){if(e.key.startsWith("Arrow")){this.moveSnake(e.key);return;}} if(e.key===" "&&id==="pixel-platformer"&&this.y>H-190)this.vy=-500; if(e.key===" "&&id==="bomb-maze")this.bomb(); if(e.key===" "&&id==="archery")this.shoot(); }
  private guess(letter:string){if(this.guessed.has(letter)||this.over)return;this.guessed.add(letter);if(!this.word.includes(letter)){this.wrong++;if(this.wrong>=6)this.finish(false);}else if([...this.word].every(ch=>this.guessed.has(ch))){this.score+=50;this.finish(true);}this.draw();}
  private bomb(){if(!this.maze.length)return;const bx=this.x,by=this.y;this.message="Bomb set";this.time.delayedCall(900,()=>{if(this.over)return;for(let y=Math.max(1,by-2);y<=Math.min(this.maze.length-2,by+2);y++)for(let x=Math.max(1,bx-2);x<=Math.min(this.maze[0].length-2,bx+2);x++)if(Math.abs(x-bx)+Math.abs(y-by)<=2){if(this.maze[y][x]===2)this.maze[y][x]=0;for(const e of this.entities)if(e.alive&&e.kind<8&&e.x===x&&e.y===y)e.alive=false;}this.score+=8;this.message="Clear! Chain the next blast.";this.draw();});}
  private makeMath(){const a=3+Math.floor(this.random()*30),b=2+Math.floor(this.random()*18);this.question=`${a} + ${b} = ?`;this.quizAnswer=a+b;this.quizOptions=[this.quizAnswer,this.quizAnswer+3+Math.floor(this.random()*8),Math.max(0,this.quizAnswer-2-Math.floor(this.random()*8)),this.quizAnswer+11];for(let i=3;i>0;i--){const j=Math.floor(this.random()*(i+1));[this.quizOptions[i],this.quizOptions[j]]=[this.quizOptions[j],this.quizOptions[i]];}}
  private answerQuiz(choice:number){const id=this.gameInfo.id,correct=id==="math-test"?this.quizOptions[choice]===this.quizAnswer:choice===0;if(correct){this.score+=10;this.message="Correct";}else{this.lives--;this.message="Not quite";}if(id==="microsoft-trivia"||this.quizIndex>=19||this.lives<=0)this.finish(this.lives>0);else{this.quizIndex++;this.makeMath();}this.draw();}
  private moveSnake(key:string){const h=this.entities[0];const d:{[key:string]:[number,number]}={ArrowUp:[0,-1],ArrowDown:[0,1],ArrowLeft:[-1,0],ArrowRight:[1,0]};const [dx,dy]=d[key]??[0,0];h.x+=dx;h.y+=dy;if(h.x<0||h.x>17||h.y<1||h.y>14||this.entities.slice(1,4).some(v=>v.x===h.x&&v.y===h.y)){this.finish(false);return;}const food=this.entities.find(v=>v.kind===1&&v.alive);if(food&&food.x===h.x&&food.y===h.y){food.alive=false;this.score+=10;const tail=this.entities[this.entities.length-1];this.entities.splice(1,0,{...tail});this.spawnEntity(1);}for(let i=this.entities.length-1;i>1;i--){this.entities[i].x=this.entities[i-1].x;this.entities[i].y=this.entities[i-1].y;} }
  private move2048(key:string){const left=key==="ArrowLeft",right=key==="ArrowRight",up=key==="ArrowUp";const rotated=Array.from({length:4},(_,y)=>Array.from({length:4},(_,x)=>up?this.cells[x][y]:this.cells[y][x]));for(let y=0;y<4;y++){let row=rotated[y].filter(Boolean);if(right||key==="ArrowDown")row.reverse();for(let i=0;i<row.length-1;i++)if(row[i]===row[i+1]){row[i]*=2;this.score+=row[i];row.splice(i+1,1);}while(row.length<4)row.push(0);if(right||key==="ArrowDown")row.reverse();for(let x=0;x<4;x++){if(up||key==="ArrowDown")this.cells[x][y]=row[x];else this.cells[y][x]=row[x];}}this.spawn2048();if(this.cells.flat().every(Boolean))this.finish(false); }
  private click(px:number,py:number){if(this.over){this.scene.restart({gameInfo:this.gameInfo,difficulty:this.difficulty,seed:patternSeed(this.gameInfo.id)});return;}const id=this.gameInfo.id;
    if(id==="hangman"){const x=Math.floor((px-175)/55),y=Math.floor((py-360)/49),index=y*10+x;if(x>=0&&x<10&&index>=0&&index<26)this.guess(String.fromCharCode(65+index));}
    else if(id==="math-test"||id==="microsoft-trivia"){const col=Math.floor((px-185)/265),row=Math.floor((py-265)/78),choice=row*2+col;if(col>=0&&col<2&&row>=0&&row<2)this.answerQuiz(choice);}
    else if(id==="nuts-and-bolts"){const idx=Math.floor((px-185)/106);if(idx<0||idx>=5)return;if(!this.chosen.length){if(this.cells[idx].length)this.chosen=[idx];}else{const from=this.chosen[0],src=this.cells[from],dst=this.cells[idx];if(from!==idx&&src.length&&(dst.length===0||dst.at(-1)===src.at(-1))&&dst.length<4){dst.push(src.pop()!);this.score+=2;if(this.cells.filter(stack=>stack.length===4&&stack.every(value=>value===stack[0])).length===4)this.finish(true);}this.chosen=[];}}
    else if(id==="circuit-break"){const s=46,ox=(W-7*s)/2,oy=118,x=Math.floor((px-ox)/s),y=Math.floor((py-oy)/s);if(this.cells[y]?.[x]!==undefined){this.cells[y][x]=(this.cells[y][x]+1)%4;this.score++;if(this.cells[3].every(value=>value===1))this.finish(true);}}
    else if(id==="minesweeper"){const n=this.cells.length,s=Math.min(43,Math.floor(370/n)),ox=(W-s*n)/2,oy=90;const x=Math.floor((px-ox)/s),y=Math.floor((py-oy)/s);if(!this.cells[y]||this.cells[y][x]===undefined)return;if(this.flags[y][x])return;if(this.cells[y][x]===-1){this.revealed[y][x]=true;this.finish(false);}else{this.reveal(x,y);if(this.revealed.flat().every((v,i)=>v||this.cells.flat()[i]===-1))this.finish(true);} }
    else if(id==="memory-match"){const s=90,ox=(W-4*s)/2,oy=92,x=Math.floor((px-ox)/s),y=Math.floor((py-oy)/s),i=y*4+x;if(i<0||i>=16||this.matches[i]||this.chosen.includes(i))return;this.chosen.push(i);if(this.chosen.length===2){const [a,b]=this.chosen;this.score+=this.cells[0][a]===this.cells[0][b]?20:0;this.time.delayedCall(550,()=>{if(this.cells[0][a]===this.cells[0][b])this.matches[a]=this.matches[b]=true;this.chosen=[];if(this.matches.every(Boolean))this.finish(true);this.draw();});} }
    else if(id==="whack-a-mole"){const mole=this.entities.find(e=>e.alive&&Math.hypot(e.x-px,e.y-py)<35);if(mole){mole.alive=false;this.score+=10+this.combo++*2;this.time.delayedCall(300,()=>this.spawnEntity(3));} }
    else if(id==="tower-defense"){this.entities.push({x:px,y:py,kind:9,alive:true,timer:0});this.score=Math.max(0,this.score-5);}
    else if(id==="bubble-pop"){const aim=this.entities.filter(e=>e.alive).sort((a,b)=>Math.abs(a.x*55+130-px)-Math.abs(b.x*55+130-px))[0];if(aim){const color=aim.kind;let hits=0;for(const e of this.entities)if(e.alive&&e.kind===color&&Math.abs(e.x-aim.x)+Math.abs(e.y-aim.y)<4){e.alive=false;hits++;}if(hits>=3)this.score+=hits*5;else this.entities.push({x:Math.floor((px-120)/50),y:9,kind:this.target,alive:true,timer:0});this.target=Math.floor(this.random()*5);} }
    else if(id==="fishing-frenzy"){if(this.phase===0){this.phase=1;this.message="Wait for the bite…";this.time.delayedCall(800+this.random()*2200,()=>{if(!this.over){this.phase=2;this.message="BITE! TAP NOW";}});}else if(this.phase===2){this.phase=0;this.score+=Math.max(5,40-Math.floor((this.elapsed%1)*35));this.message="Nice catch! Cast again.";}else if(this.phase===1){this.score=Math.max(0,this.score-4);this.message="Too early. Try again.";this.phase=0;} }
    else if(id==="archery"||id==="toon-toss"){this.x=px;this.y=py;this.shoot();}
    else if(id==="tic-tac-toe"){const s=120,ox=(W-3*s)/2,oy=90,x=Math.floor((px-ox)/s),y=Math.floor((py-oy)/s),i=y*3+x;if(x<0||x>2||y<0||y>2||!this.cells[y]){if(!this.cells.length)this.cells=Array.from({length:3},()=>Array(3).fill(0));}if(this.cells[y]?.[x]===0){this.cells[y][x]=1;this.score+=10;const empty=this.cells.flatMap((row,yy)=>row.map((v,xx)=>v===0?[xx,yy] as [number,number]:null).filter((v):v is [number,number]=>v!==null));if(empty.length){const [cx,cy]=empty[Math.floor(this.random()*empty.length)];this.cells[cy][cx]=2;}} }
    else if(id==="snake"||id==="snake-arena"){const gx=Math.floor((px-138)/37),gy=Math.floor((py-95)/29),h=this.entities[0];if(Math.abs(gx-h.x)>Math.abs(gy-h.y))this.moveSnake(gx<h.x?"ArrowLeft":"ArrowRight");else this.moveSnake(gy<h.y?"ArrowUp":"ArrowDown");}
    else if(this.maze.length){const tw=this.tile,ox=(W-this.maze[0].length*tw)/2,oy=65;const cx=Math.floor((px-ox)/tw),cy=Math.floor((py-oy)/tw);if(Math.abs(cx-this.x)+Math.abs(cy-this.y)===1)this.stepMaze(cx,cy);}
    else if(id==="color-hunter"){const e=this.entities.find(v=>v.alive&&Math.hypot(v.x-px,v.y-py)<32);if(e){if(e.kind===this.target){e.alive=false;this.score+=10;this.target=Math.floor(this.random()*5);this.spawnEntity(Math.floor(this.random()*5));}else this.lives--;}}
    else if(id==="platformer") this.vy=-450;
    else if(id==="space-shooter"||id==="action-arena"){this.x=px;this.y=py;this.score+=1;}
    else if(id==="pixel-platformer"){this.vy=-430;}
    this.draw();
  }
  private reveal(x:number,y:number){if(this.revealed[y]?.[x]||this.flags[y]?.[x])return;this.revealed[y][x]=true;if(!this.cells[y][x])for(const [a,b] of this.neighbors(x,y))this.reveal(a,b);}
  private stepMaze(x:number,y:number){if(this.maze[y]?.[x]===1)return;if(this.maze[y]?.[x]===2){this.maze[y][x]=0;this.score+=2;}if(this.maze[y]?.[x]===3){this.maze[y][x]=0;this.score+=10;this.message=this.gameInfo.id==="escape-the-maze"?`Key ${Math.min(3,Math.floor(this.score/10))} of 3`:"Treasure collected";}this.x=x;this.y=y;const id=this.gameInfo.id;if((id==="treasure-escape"&&this.score>=30||id==="escape-the-maze"&&this.score>=30)&&x===this.maze[0].length-2&&y===this.maze.length-2)this.finish(true);else if(id==="ghost-maze"||id==="maze-chase"||id==="treasure-escape"||id==="robot-hunt"){if(this.entities.some(e=>e.alive&&e.x===x&&e.y===y))this.finish(false);}if((id==="ghost-maze"||id==="maze-chase")&&this.score>=180)this.finish(true);if(id==="infinite-maze")this.score++;if(id==="bomb-maze")this.score+=1;}
  private shoot(){if(this.gameInfo.id==="archery"){const dx=this.x-W/2,dy=this.y-120;const accuracy=Math.max(0,100-Math.floor(Math.hypot(dx,dy)/3));this.score+=accuracy;this.message=`${accuracy} points · wind ${Math.round((this.random()-.5)*18)} mph`;this.x=W/2;this.y=H-80;}else{this.score+=Math.max(1,Math.floor(this.random()*15));this.message="Good shot! Set up the next one.";}}
  private finish(win:boolean){if(this.over)return;this.over=true;this.message=win?"Round cleared!":"Round over";this.draw();}
  update(_time:number,dt:number){if(this.over)return;const id=this.gameInfo.id,s=dt/1000;this.elapsed+=s;
    if(["snake","snake-arena"].includes(id)&&Math.floor(this.elapsed*3)!==Math.floor((this.elapsed-s)*3))this.moveSnake(this.keys.LEFT.isDown?"ArrowLeft":this.keys.RIGHT.isDown?"ArrowRight":this.keys.UP.isDown?"ArrowUp":this.keys.DOWN.isDown?"ArrowDown":"");
    if(id==="pixel-platformer"){const dir=(this.keys.LEFT.isDown||this.keys.A.isDown)?-1:(this.keys.RIGHT.isDown||this.keys.D.isDown)?1:0;this.x=Phaser.Math.Clamp(this.x+dir*230*s,20,W-20);const oldY=this.y;this.vy+=1000*s;this.y+=this.vy*s;for(const p of this.entities)if(p.alive&&p.kind===0&&this.vy>=0&&oldY<=p.y-17&&this.y>=p.y-17&&Math.abs(this.x-p.x)<38){this.y=p.y-18;this.vy=0;}if(this.y>H-105){this.y=H-105;this.vy=0;}for(const e of this.entities)if(e.alive&&e.kind===2&&Math.hypot(e.x-this.x,e.y-this.y)<24){e.alive=false;this.score+=50;}if(this.x>W-35){this.finish(true);}}
    if(id==="brick-breaker"){this.paddleX=Phaser.Math.Clamp(this.input.activePointer.x||this.paddleX,55,W-55);if(!this.held){this.x+=this.vx*s*60;this.y+=this.vy*s*60;if(this.x<20||this.x>W-20)this.vx*=-1;if(this.y<40)this.vy=Math.abs(this.vy);if(this.y>H-65&&Math.abs(this.x-this.paddleX)<90)this.vy=-Math.abs(this.vy);if(this.y>H){this.lives--;this.x=W/2;this.y=H-75;this.vy=-4;if(this.lives<=0)this.finish(false);}for(const e of this.entities)if(e.alive&&Math.abs(e.x-this.x)<30&&Math.abs(e.y-this.y)<13){e.alive=false;this.vy*=-1;this.score+=5;}}}
    if(id==="space-shooter"){this.x=Phaser.Math.Clamp(this.x+((this.keys.LEFT.isDown?-1:0)+(this.keys.RIGHT.isDown?1:0))*280*s,25,W-25);if(Math.floor(this.elapsed*1.5)!==Math.floor((this.elapsed-s)*1.5))this.entities.push({x:this.x,y:this.y-30,kind:10,alive:true,timer:0});for(const e of this.entities){e.y+=e.kind===2?70*s:-340*s;if(e.kind===2&&e.y>H)e.alive=false;if(e.kind===2&&Math.abs(e.x-this.x)<22&&Math.abs(e.y-this.y)<30)this.lives--;}if(this.lives<=0)this.finish(false);if(this.entities.filter(e=>e.kind===2).length<4&&this.random()<.03)this.spawnEntity(2);this.score+=Math.floor(s*4);}
    if(id==="action-arena"){const dx=(this.keys.RIGHT.isDown?1:0)-(this.keys.LEFT.isDown?1:0),dy=(this.keys.DOWN.isDown?1:0)-(this.keys.UP.isDown?1:0);this.x=Phaser.Math.Clamp(this.x+dx*210*s,25,W-25);this.y=Phaser.Math.Clamp(this.y+dy*210*s,55,H-25);for(const e of this.entities){e.x+=Math.sign(this.x-e.x)*48*s;e.y+=Math.sign(this.y-e.y)*48*s;if(Math.hypot(e.x-this.x,e.y-this.y)<28){this.lives-=s*.8;if(this.lives<=0)this.finish(false);}}if(Math.floor(this.elapsed/7)!==Math.floor((this.elapsed-s)/7))this.spawnEntity(2);this.score+=Math.floor(s*2);}
    if(this.maze.length&&Math.floor(this.elapsed*1.2)!==Math.floor((this.elapsed-s)*1.2)){for(const e of this.entities){if(e.kind===8||e.kind===11)continue;const opts=[[e.x+1,e.y],[e.x-1,e.y],[e.x,e.y+1],[e.x,e.y-1]].filter(([x,y])=>this.maze[y]?.[x]===0);if(opts.length){opts.sort((a,b)=>Math.abs(a[0]-this.x)+Math.abs(a[1]-this.y)-Math.abs(b[0]-this.x)-Math.abs(b[1]-this.y));const smart=id==="robot-hunt"?e.kind%2===0:this.random()<.72;const [x,y]=smart?opts[0]:opts[Math.floor(this.random()*opts.length)];e.x=x;e.y=y;}if(e.x===this.x&&e.y===this.y)this.finish(false);}if(id==="rising-lava"&&this.elapsed>25)this.lives-=.015;}
    if(id==="tower-defense"){for(const e of this.entities)if(e.kind===1){e.x+=40*s;if(e.x>W+60){e.x=-60;e.y=150+this.random()*180;this.lives--;}}for(const t of this.entities.filter(e=>e.kind===9))if(this.random()<s*.5){const enemy=this.entities.find(e=>e.kind===1&&e.alive&&Math.hypot(e.x-t.x,e.y-t.y)<180);if(enemy){enemy.alive=false;this.score+=15;this.time.delayedCall(1000,()=>{if(!this.over)this.spawnEntity(1);});}}if(this.lives<=0)this.finish(false);}
    if(id==="whack-a-mole"&&!this.entities.some(e=>e.alive)&&Math.floor(this.elapsed)!==Math.floor(this.elapsed-s))this.spawnEntity(3);
    if(id==="infinite-maze"&&Math.floor(this.elapsed/20)!==Math.floor((this.elapsed-s)/20)){this.maze=makeMaze(this.seed+Math.floor(this.elapsed/20));this.x=1;this.y=1;this.score+=10;}
    if(id==="shadow-chase"&&Math.floor(this.elapsed/8)!==Math.floor((this.elapsed-s)/8)){this.entities.push({x:this.x,y:this.y,kind:11,alive:true,timer:0});if(this.entities.length>12)this.entities.splice(0,1);}
    if(id==="bubble-pop"&&this.entities.filter(e=>e.alive).length===0)this.finish(true);
    if(id==="2048"&&this.cells.flat().some(v=>v>=2048))this.finish(true);
    if(id==="hangman"||id==="math-test"||id==="microsoft-trivia")this.score+=0;
    this.draw();
  }
  private draw(){const g=this.g,id=this.gameInfo.id;this.labelCursor=0;g.clear();g.fillStyle(paper,1).fillRoundedRect(0,0,W,H,12);g.fillStyle(0xf8f6f0,1).fillRoundedRect(14,60,W-28,H-74,16);
    // faint warm lighting and restrained paper grain
    for(let i=0;i<18;i++){const x=(i*97+this.seed*7)%W,y=(i*67+this.seed*11)%H;g.fillStyle(0xb5a992,.035).fillCircle(x,y,1.4);}
    if(id==="minesweeper")this.drawMines();else if(id==="memory-match")this.drawMemory();else if(id==="2048")this.draw2048();else if(id==="snake"||id==="snake-arena")this.drawSnake();else if(this.maze.length)this.drawMaze();else if(id==="brick-breaker")this.drawBricks();else if(id==="bubble-pop")this.drawBubbles();else if(id==="space-shooter")this.drawSpace();else if(id==="pixel-platformer")this.drawPlatform();else if(id==="tower-defense")this.drawTower();else if(id==="whack-a-mole")this.drawMoles();else if(id==="fishing-frenzy")this.drawFishing();else if(id==="archery"||id==="toon-toss")this.drawArchery();else if(id==="tic-tac-toe")this.drawTic();else if(id==="hangman")this.drawHangman();else if(id==="math-test"||id==="microsoft-trivia")this.drawQuiz();else if(id==="nuts-and-bolts")this.drawNuts();else if(id==="circuit-break")this.drawCircuit();else this.drawAction();
    const lines=this.hud;lines.setText(`${this.gameInfo.title.toUpperCase()}     SCORE  ${this.score}     ${"● ".repeat(Math.max(0,Math.ceil(this.lives)))}     PATTERN ${this.seed.toString().padStart(3,"0")}/256`);
    for(let i=this.labelCursor;i<this.labels.length;i++)this.labels[i].setVisible(false);
    if(this.message){g.fillStyle(ink,.9).fillRoundedRect(W/2-190,H-54,380,34,10);this.label(W/2,H-37,this.message,{fontFamily:"Arial",fontSize:"15px",color:"#ffffff",fontStyle:"bold"}).setOrigin(.5);}
    if(this.over){g.fillStyle(0x101719,.76).fillRoundedRect(0,60,W,H-74,14);this.label(W/2,H/2-14,this.message,{fontFamily:"Arial",fontSize:"34px",color:"#fff8e9",fontStyle:"bold"}).setOrigin(.5);this.label(W/2,H/2+31,`Final score  ${this.score}   ·   Tap to play another pattern`,{fontFamily:"Arial",fontSize:"17px",color:"#e8d5ad"}).setOrigin(.5);}
  }
  private drawMines(){const n=this.cells.length,s=Math.min(43,Math.floor(370/n)),ox=(W-s*n)/2,oy=100;for(let y=0;y<n;y++)for(let x=0;x<n;x++){const open=this.revealed[y]?.[x];this.g.fillStyle(open?0xdad4c8:0xa6b6b3,1).fillRoundedRect(ox+x*s+2,oy+y*s+2,s-4,s-4,4);if(open&&this.cells[y][x])this.label(ox+x*s+s/2,oy+y*s+s/2,this.cells[y][x]===-1?"✹":String(this.cells[y][x]),{fontSize:"18px",color:this.cells[y][x]===-1?"#ae4437":"#35556b",fontStyle:"bold"}).setOrigin(.5);}}
  private drawMemory(){const s=90,ox=(W-4*s)/2,oy=95;for(let i=0;i<16;i++){const x=ox+(i%4)*s,y=oy+Math.floor(i/4)*s,open=this.matches[i]||this.chosen.includes(i);this.g.fillStyle(open?0xd6c9aa:0x7d9da0,1).fillRoundedRect(x+4,y+4,s-8,s-8,9);this.label(x+s/2,y+s/2,open?String.fromCharCode(65+this.cells[0][i]):"?",{fontSize:"28px",color:open?"#353a36":"#fff",fontStyle:"bold"}).setOrigin(.5);}}
  private draw2048(){const s=90,ox=(W-4*s)/2,oy=96,cols=[0xe9dfc9,0xdfc89f,0xdaa778,0xc98968,0xb96d59,0x879b91,0x73929a];for(let y=0;y<4;y++)for(let x=0;x<4;x++){const v=this.cells[y][x];this.g.fillStyle(v?cols[Math.min(cols.length-1,Math.log2(v)-1)]:0xd9d4c9,1).fillRoundedRect(ox+x*s+4,oy+y*s+4,s-8,s-8,10);if(v)this.label(ox+x*s+s/2,oy+y*s+s/2,String(v),{fontSize:v>999?"25px":"32px",color:"#303333",fontStyle:"bold"}).setOrigin(.5);}}
  private drawSnake(){for(let y=1;y<15;y++)for(let x=0;x<18;x++){this.g.fillStyle(0x8b9b85,.08).fillRoundedRect(120+x*37,80+y*29,34,26,3);}for(let i=this.entities.length-1;i>=0;i--){const e=this.entities[i];if(!e.alive)continue;const x=138+e.x*37,y=95+e.y*29;this.g.fillStyle(e.kind===1?red:i===0?0x416b59:green,1).fillRoundedRect(x-12,y-10,24,20,8);}}
  private drawMaze(){const m=this.maze,tw=this.tile,ox=(W-m[0].length*tw)/2,oy=66;for(let y=0;y<m.length;y++)for(let x=0;x<m[0].length;x++){this.g.fillStyle(m[y][x]===1?0x53656a:m[y][x]===2?0xb99055:0xe7e1d4,1).fillRoundedRect(ox+x*tw,oy+y*tw,tw-1,tw-1,3);if(m[y][x]===3)this.g.fillStyle(gold,1).fillCircle(ox+x*tw+tw/2,oy+y*tw+tw/2,tw*.16);}this.g.fillStyle(gold,1).fillCircle(ox+(m[0].length-2)*tw+tw/2,oy+(m.length-2)*tw+tw/2,tw*.23);this.g.fillStyle(blue,1).fillRoundedRect(ox+this.x*tw+7,oy+this.y*tw+6,tw-14,tw-12,7);for(const e of this.entities)if(e.alive&&e.kind<8)this.g.fillStyle(e.kind===5?0x65777c:e.kind===4?gold:red,1).fillCircle(ox+e.x*tw+tw/2,oy+e.y*tw+tw/2,tw*.32);for(const e of this.entities)if(e.alive&&e.kind===11)this.g.fillStyle(0x696779,.55).fillCircle(ox+e.x*tw+tw/2,oy+e.y*tw+tw/2,tw*.28);if(this.gameInfo.id==="rising-lava"){const rise=Math.min(H-100,this.elapsed*2.5);this.g.fillStyle(0xd96744,.6).fillRect(0,H-rise,W,rise);if(rise>H-100-this.y*tw)this.finish(false);}}
  private drawBricks(){this.g.fillStyle(0x839a9b,1).fillRoundedRect(this.paddleX-66,H-55,132,15,7);for(const e of this.entities)if(e.alive)this.g.fillStyle([red,gold,blue,green][e.kind],1).fillRoundedRect(e.x-27,e.y-10,54,20,5);this.g.fillStyle(0xfff4dc,1).fillCircle(this.x,this.y,10);}
  private drawBubbles(){for(const e of this.entities)if(e.alive){const x=132+e.x*50,y=85+e.y*40;this.g.fillStyle([red,blue,green,gold,0x9a79aa][e.kind],1).fillCircle(x,y,17);this.g.lineStyle(3,0xffffff,.3).strokeCircle(x-3,y-4,9);}this.g.fillStyle([red,blue,green,gold,0x9a79aa][this.target],1).fillCircle(W/2,H-70,20);this.g.lineStyle(2,ink,.4).lineBetween(W/2,H-50,this.input.activePointer.x,this.input.activePointer.y);}
  private drawSpace(){this.g.fillStyle(0x26374b,1).fillRect(0,60,W,H-74);for(let i=0;i<70;i++){const x=(i*137+this.seed*13)%W,y=(i*67+this.elapsed*35)%H;this.g.fillStyle(0xffffff,.38).fillCircle(x,y,1.2);}this.g.fillStyle(blue,1).fillTriangle(this.x,this.y-23,this.x-19,this.y+20,this.x+19,this.y+20);for(const e of this.entities)if(e.alive)this.g.fillStyle(e.kind===2?red:gold,1).fillCircle(e.x,e.y,e.kind===2?13:4);}
  private drawPlatform(){this.g.fillStyle(0x9bb8bc,1).fillRect(15,68,W-30,H-92);this.g.fillStyle(0x78856c,1).fillRect(15,H-80,W-30,65);for(const e of this.entities)if(e.alive){this.g.fillStyle(e.kind===2?gold:0x89977d,1).fillRoundedRect(e.x-27,e.y-10,55,20,5);if(e.kind===2)this.g.fillStyle(gold,1).fillCircle(e.x,e.y-17,8);}this.stickman(this.x,this.y);}
  private drawTower(){this.g.fillStyle(0xc5d1be,1).fillRoundedRect(105,145,690,265,22);this.g.lineStyle(34,0x9a927b,.8);this.g.beginPath();this.g.moveTo(60,275);this.g.lineTo(250,275);this.g.lineTo(250,180);this.g.lineTo(460,180);this.g.lineTo(460,355);this.g.lineTo(690,355);this.g.lineTo(690,260);this.g.lineTo(845,260);this.g.strokePath();for(const e of this.entities)if(e.alive){this.g.fillStyle(e.kind===1?red:green,1).fillCircle(e.x,e.y,e.kind===1?12:16);}this.g.fillStyle(ink,.7).fillRoundedRect(28,490,170,35,8);this.label(42,497,"Tap to place tower",{fontSize:"16px",color:"#fff"});}
  private drawMoles(){for(let y=0;y<3;y++)for(let x=0;x<4;x++){const cx=290+x*105,cy=155+y*105;this.g.fillStyle(0x74614c,1).fillEllipse(cx,cy+15,75,45);this.g.fillStyle(0x867868,1).fillEllipse(cx,cy+13,63,33);}for(const e of this.entities)if(e.alive){this.g.fillStyle(0x9b7658,1).fillCircle(e.x,e.y,25);this.g.fillStyle(ink,1).fillCircle(e.x-8,e.y-4,2);this.g.fillStyle(ink,1).fillCircle(e.x+8,e.y-4,2);}}
  private drawFishing(){this.g.fillStyle(0x7daeb4,1).fillRect(20,90,W-40,H-110);for(let y=0;y<7;y++)this.g.lineStyle(2,0xffffff,.11).lineBetween(40,140+y*48,W-40,140+y*48);this.g.lineStyle(5,0x755e47,1).lineBetween(80,115,250,290);this.g.lineStyle(2,ink,.8).lineBetween(250,290,440,365+Math.sin(this.elapsed*2)*20);this.g.fillStyle(gold,1).fillTriangle(435,355,448,365,435,375);this.label(W/2,475,this.message||"Tap to cast · tap again when the float dips",{fontSize:"20px",color:"#25414a",fontStyle:"bold"}).setOrigin(.5);}
  private drawArchery(){this.g.fillStyle(0xded5c3,1).fillRect(20,70,W-40,H-95);this.g.lineStyle(2,0x84775f,.6).lineBetween(120,410,800,410);this.g.fillStyle(0x8e7657,1).fillRect(120,200,12,215);const tx=650+(this.seed%15)-7,ty=245+((this.seed*7)%15)-7;for(let r=66;r>0;r-=22){this.g.fillStyle(r===66?0xeee5d2:r===44?red:r===22?gold:ink,1).fillCircle(tx,ty,r);}this.g.lineStyle(3,ink,1).lineBetween(125,290,this.input.activePointer.x||tx,this.input.activePointer.y||ty);this.stickman(112,370);this.label(460,440,"Aim with your pointer · click to shoot",{fontSize:"18px",color:"#41433c"}).setOrigin(.5);}
  private drawTic(){const s=120,ox=(W-3*s)/2,oy=95;if(!this.cells.length)this.cells=Array.from({length:3},()=>Array(3).fill(0));for(let y=0;y<3;y++)for(let x=0;x<3;x++){this.g.fillStyle(0xdad4c7,1).fillRoundedRect(ox+x*s+4,oy+y*s+4,s-8,s-8,10);const v=this.cells[y]?.[x];if(v)this.label(ox+x*s+s/2,oy+y*s+s/2,v===1?"×":"○",{fontSize:"65px",color:v===1?"#708e93":"#b87b64",fontStyle:"bold"}).setOrigin(.5);}}
  private drawNuts(){const colors=[red,blue,green,gold],names=["CORAL","BLUE","GREEN","GOLD","EMPTY"];for(let x=0;x<5;x++){const px=210+x*106,selected=this.chosen[0]===x;this.g.fillStyle(selected?0xd5c5a1:0xe1ddd4,1).fillRoundedRect(px-34,135,68,300,12);this.label(px,455,names[x]??"STACK",{fontSize:"12px",color:"#555c5a",fontStyle:"bold"}).setOrigin(.5);for(let i=0;i<this.cells[x].length;i++){const value=this.cells[x][i];this.g.fillStyle(colors[value],1).fillRoundedRect(px-27,395-i*57,54,47,15);this.g.fillStyle(0x202625,.65).fillCircle(px,418-i*57,11);this.g.fillStyle(0xe3d9c5,1).fillCircle(px,418-i*57,5);}}this.label(W/2,505,"Move a top piece onto its color · one empty stack",{fontSize:"16px",color:"#555c5a"}).setOrigin(.5);}
  private drawCircuit(){const s=46,ox=(W-7*s)/2,oy=118;for(let y=0;y<7;y++)for(let x=0;x<7;x++){this.g.fillStyle((x===0&&y===3)||(x===6&&y===3)?gold:0xd8d3c7,1).fillRoundedRect(ox+x*s+2,oy+y*s+2,s-4,s-4,7);const t=this.cells[y][x];this.g.lineStyle(5,(x===0&&y===3)||(x===6&&y===3)?0x394447:0x77948c,1);if(t===0||t===2)this.g.lineBetween(ox+x*s+s/2,oy+y*s+8,ox+x*s+s/2,oy+y*s+s-8);if(t===1||t===3)this.g.lineBetween(ox+x*s+8,oy+y*s+s/2,ox+x*s+s-8,oy+y*s+s/2);}this.label(W/2,470,"Click tiles to rotate · connect the source across the center row",{fontSize:"16px",color:"#555c5a"}).setOrigin(.5);}
  private drawHangman(){this.g.lineStyle(6,0x777367,1).lineBetween(270,425,550,425).lineBetween(335,425,335,120).lineBetween(335,120,505,120).lineBetween(505,120,505,155);const parts=[[505,178,20],[505,228,0],[480,216,0],[530,216,0],[488,265,0],[522,265,0]];for(let i=0;i<this.wrong;i++){const [x,y,type]=parts[i];this.g.lineStyle(5,0x3f4849,1);if(type)this.g.strokeCircle(x,y,21);else if(i===1)this.g.lineBetween(x,y-22,x,y+30);else if(i===2||i===3)this.g.lineBetween(505,205,x,y);else this.g.lineBetween(505,245,x,y);}const start=(W-this.word.length*48)/2;for(let i=0;i<this.word.length;i++)this.label(start+i*48,330,this.guessed.has(this.word[i])||this.over?this.word[i]:"_",{fontSize:"28px",color:"#394446",fontStyle:"bold"}).setOrigin(.5);for(let i=0;i<26;i++){const x=190+(i%10)*55,y=390+Math.floor(i/10)*48,letter=String.fromCharCode(65+i),disabled=this.guessed.has(letter);this.g.fillStyle(disabled?0xd7d2c9:0x819b94,1).fillRoundedRect(x,y,44,37,5);this.label(x+22,y+18,letter,{fontSize:"15px",color:disabled?"#8a8982":"#fff",fontStyle:"bold"}).setOrigin(.5);}this.label(W/2,510,`Wrong guesses  ${this.wrong} / 6`,{fontSize:"14px",color:"#5f6867"}).setOrigin(.5);}
  private drawQuiz(){this.label(W/2,135,this.gameInfo.id==="math-test"?`ROUND ${this.quizIndex+1} / 20`:"QUICK TRIVIA",{fontSize:"14px",color:"#71847e",fontStyle:"bold"}).setOrigin(.5);this.label(W/2,205,this.question,{fontSize:"29px",color:"#303839",fontStyle:"bold",align:"center",wordWrap:{width:680}}).setOrigin(.5);for(let i=0;i<4;i++){const x=190+(i%2)*265,y=270+Math.floor(i/2)*78;this.g.fillStyle(0xd9e1d9,1).fillRoundedRect(x,y,240,58,9);const text=this.gameInfo.id==="math-test"?String(this.quizOptions[i]??"?"):this.quizTextOptions[this.quizOptions[i]??0];this.label(x+120,y+29,`${i+1}   ${text}`,{fontSize:"18px",color:"#36413f",fontStyle:"bold"}).setOrigin(.5);}}
  private drawAction(){const isColor=this.gameInfo.id==="color-hunter";if(isColor)this.label(W/2,93,`COLLECT  ${["CORAL","BLUE","GREEN","GOLD","VIOLET"][this.target]}`,{fontSize:"25px",color:"#41433d",fontStyle:"bold"}).setOrigin(.5);for(const e of this.entities)if(e.alive){const color=e.kind===4?gold:e.kind===5?0x75898e:e.kind===6?red:e.kind===7?ink:e.kind===8?0x8d8d9d:[red,blue,green,gold,0x9a79aa][e.kind%5];this.g.fillStyle(color,1).fillCircle(e.x,e.y,e.kind===2?16:23);if(e.kind===2)this.g.fillStyle(0xf1e7d5,1).fillTriangle(e.x,e.y-12,e.x-11,e.y+10,e.x+11,e.y+10);}if(this.gameInfo.id==="toon-toss")this.stickman(150,H-130);}
  private stickman(x:number,y:number){this.g.lineStyle(6,0x363b3d,1);this.g.strokeCircle(x,y-43,12);this.g.lineBetween(x,y-30,x,y+4);this.g.lineBetween(x,y-18,x-17,y-4);this.g.lineBetween(x,y-18,x+18,y-8);this.g.lineBetween(x,y+4,x-13,y+23);this.g.lineBetween(x,y+4,x+14,y+23);}
}

export function mountPhaserGame(root: HTMLElement, options: { game: GameInfo; difficulty: Difficulty; replay: () => void; chooseDifficulty: () => void }) {
  let game: Phaser.Game | null = null; let disposed=false;
  const pattern=patternSeed(options.game.id);
  root.innerHTML=`<section class="phaser-game-shell"><header class="phaser-game-bar"><div><span class="arcade-overline">2D ORIGINAL · ${options.difficulty.toUpperCase()} · PATTERN ${String(pattern).padStart(3,"0")}/256</span><h2>${options.game.title}</h2></div><button class="arcade-menu-button" data-phaser-menu>Change difficulty</button></header><div class="phaser-stage" aria-label="${options.game.title} game area"></div><div class="phaser-help">${help(options.game.id)} <span>· Random layout ${String(pattern).padStart(3,"0")} of 256</span></div><footer class="arcade-game-footer"><span>${options.difficulty.toUpperCase()} CHALLENGE</span><span>PLAY SESSION · SCORE IS NOT SAVED</span></footer></section>`;
  const stage=root.querySelector<HTMLElement>(".phaser-stage")!;
  CasualScene.bootData={gameInfo:options.game,difficulty:options.difficulty,seed:pattern};
  game=new Phaser.Game({type:Phaser.AUTO,parent:stage,width:W,height:H,backgroundColor:"#e9e4d8",antialias:true,roundPixels:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[CasualScene],render:{pixelArt:false,antialias:true}});
  root.querySelector("[data-phaser-menu]")!.addEventListener("click",options.chooseDifficulty);
  return ()=>{if(disposed)return;disposed=true;game?.destroy(true);game=null;root.innerHTML="";};
}
function help(id:string){const copy:Record<string,string>={"pixel-platformer":"Move with A/D or the arrow keys · Space or tap to jump","snake":"Arrow keys steer the snake","snake-arena":"Arrow keys steer · avoid your tail and rivals","2048":"Arrow keys slide and combine the tiles","minesweeper":"Click a tile to reveal it","memory-match":"Click cards to turn them over","whack-a-mole":"Tap a mole as soon as it appears","brick-breaker":"Move your pointer to steer the paddle","bubble-pop":"Click a bubble cluster to clear matching colors","tower-defense":"Tap open ground to place a tower","space-shooter":"Move with left and right arrows","action-arena":"Move with arrow keys · survive the wave","fishing-frenzy":"Tap to cast, then tap again when the float dips","archery":"Aim with the pointer and click to shoot","toon-toss":"Choose an aim point and click to throw","tic-tac-toe":"Click a square to make your move","ghost-maze":"Move one tile at a time with the arrow keys","treasure-escape":"Collect treasure, then reach the glowing exit","infinite-maze":"Find a route through each shifting maze","robot-hunt":"Move with arrow keys and avoid patrols","rising-lava":"Move through the maze before the lava rises","shadow-chase":"Keep moving; past positions return as shadows","bomb-maze":"Move with arrows · Space sets a bomb","color-hunter":"Tap objects that match the color shown","escape-the-maze":"Find the keys and reach the exit"};return copy[id]??"Click or tap to play · Arrow keys move";}
